package com.saneb.domain.announcementattachment.qa;
import static org.assertj.core.api.Assertions.*;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.CapitalEighthNoticePage;
import com.saneb.domain.announcementsource.provider.content.CapitalEighthNoticePage.Site;
import java.net.URI;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
class CapitalEighthDownloadContractTest {
    private String item(String group,int id,String ext){if(group.equals("PAJU")){String key="00000000-0000-0000-0000-"+String.format("%012d",id);return "<li><i class='ico ico-file-"+ext+"'></i><span class=sr-only>"+ext+"</span><a href='/component/file/ND_fileDownload.do?id="+key+"'>지원 공고."+ext+"</a><a href='/component/file/ND_fileViewer.do?id="+key+"'>바로보기</a></li>";}return "fileList.push({\"sysFileNm\":\"file"+id+"."+ext+"\",\"fileNm\":\"지원 공고."+ext+"\",\"filePath\":\"/ntishome/file/upload/ofr/ofr/20260320\",\"fileId\":\""+id+"\"});";}
    private String page(String group,String items){return group.equals("PAJU")?"<article id=content><div class=content-body><div class=container><div class=article-view><div class=article-header><div class=info-area><h1 class=article-subject><span class=category-label>고시공고</span>소상공인 지원</h1></div><ul class='file-list file-shortcut'>"+items+"</ul></div><div class=article-body><div class=article-conetnt>소상공인 지원금</div></div></div></div></div></article>":"<div class=sub_content_cont_rt_cont><form name=fileDown id=fileDown method=post action='https://eminwon.gm.go.kr/emwp/jsp/ofr/FileDownNew.jsp'><input type=hidden name=user_file_nm value=''><input type=hidden name=sys_file_nm value=''><input type=hidden name=file_path value=''></form><table class='table_style2 bbsView'><tr><th>제목</th><td>소상공인 지원</td></tr><tr><th>담당부서</th><td>수출 부서</td></tr><tr><th>첨부파일</th><td><ul id=otherList></ul></td></tr><tr><th>내용</th><td>소상공인 지원금</td></tr></table></div><script>var fileList = [];"+items+"fileList.sort(function(a,b){return Number(a.fileId)-Number(b.fileId);});var target=$(\"#otherList\");</script>";}
    @ParameterizedTest @ValueSource(strings={"PAJU","GWANGMYEONG"})
    void filesPartialErrorsDuplicatesAndLimit(String group){var s=CapitalEighthDownloadCases.selectCase(group);var p=s.profile();String good=item(group,1,"pdf")+item(group,2,"hwp")+item(group,3,"hwpx");var r=p.selectDescriptors(s.source(),page(group,good));assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(3).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(p.selectApprovedRequest(d.selectRequest(),d.selectRequest())).isTrue();});String bad=group.equals("PAJU")?"<li><a href='https://evil.example/file'>파일</a></li>":"fileList.push(loadExternal());";var partial=p.selectDescriptors(s.source(),page(group,good+bad));assertThat(partial.complete()).isFalse();assertThat(partial.descriptors()).hasSize(3);var unsupported=p.selectDescriptors(s.source(),page(group,good+item(group,4,"xlsx")));assertThat(unsupported.complete()).isTrue();assertThat(unsupported.descriptors().getLast().downloadAllowed()).isFalse();String one=item(group,1,"pdf");assertThat(p.selectDescriptors(s.source(),page(group,one+one)).descriptors()).hasSize(1);assertThat(p.selectDescriptors(s.source(),page(group,one+one.replace("지원 공고","다른 공고"))).complete()).isFalse();assertThat(p.selectDescriptors(s.source(),page(group,"")).status()).isEqualTo("NO_FILES");assertThat(p.selectDescriptors(s.source(),"<p>첨부 없음</p>").complete()).isFalse();var limited=p.selectDescriptors(s.source(),page(group,IntStream.rangeClosed(1,11).mapToObj(i->item(group,i,"pdf")).collect(Collectors.joining())));assertThat(limited.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(limited.descriptors()).hasSize(10);}
    @ParameterizedTest @ValueSource(strings={"PAJU","GWANGMYEONG"})
    void exactSourceHostAndRedirectBinding(String group){var s=CapitalEighthDownloadCases.selectCase(group);var p=s.profile();var d=p.selectDescriptors(s.source(),page(group,item(group,1,"pdf"))).descriptors().getFirst();for(String bad:List.of(d.fetchUri().toString().replace("https:","http:"),d.fetchUri().toString().replace(d.fetchUri().getHost(),"127.0.0.1"),d.fetchUri()+"#fragment","https:opaque")){var request=new Request(URI.create(bad),d.selectRequest().method(),d.postForm());assertThat(p.selectApprovedRequest(request)).isFalse();assertThat(p.selectApprovedRequest(d.selectRequest(),request)).isFalse();}var other=p.selectDescriptors(s.source(),page(group,item(group,2,"pdf"))).descriptors().getFirst();assertThat(p.selectApprovedRequest(d.selectRequest(),other.selectRequest())).isFalse();var n=new AnnouncementSourceIdentityNormalizer();for(String bad:List.of(s.source().sourceUrl()+"&extra=1",s.source().sourceUrl()+"&"+Site.valueOf(group).idKey+"=99",s.source().sourceUrl().replace("https:","http:")))assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",n.hash(n.canonicalizeUrl(bad)),bad,s.source().localSourceCode(),s.source().listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE","wrong",s.source().sourceUrl(),s.source().localSourceCode(),s.source().listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");}
    @Test void literalManifestCannotExecuteCodeOrHideFailures(){var s=CapitalEighthDownloadCases.selectCase("GWANGMYEONG");String good=item("GWANGMYEONG",1,"hwp");for(String bad:List.of("fileList.push(fetch('/private'));","fileList[0]=fetch('/private');","fileList.push({\"fileId\":\"0\",\"fileId\":\"1\",\"fileNm\":\"공고.hwp\",\"sysFileNm\":\"f.hwp\",\"filePath\":\"/ntishome/file/upload/ofr/ofr/20260320\"});",item("GWANGMYEONG",2,"hwp").replace("/ntishome/","/../ntishome/"))){var r=s.profile().selectDescriptors(s.source(),page("GWANGMYEONG",good+bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}for(String bad:List.of(page("GWANGMYEONG",good).replace("action='https://eminwon.gm.go.kr","action='https://evil.example"),page("GWANGMYEONG",good).replace("var fileList = [];","var different=[];")))assertThat(s.profile().selectDescriptors(s.source(),bad).complete()).isFalse();}
    @Test void previewMismatchRetainsDownloadButRequiresReview(){var s=CapitalEighthDownloadCases.selectCase("PAJU");var html=page("PAJU",item("PAJU",1,"pdf").replace("ND_fileViewer.do?id=00000000-0000-0000-0000-000000000001","ND_fileViewer.do?id=00000000-0000-0000-0000-000000000002"));var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);assertThat(s.profile().selectApprovedRequest(URI.create("https://www.paju.go.kr/component/file/ND_fileViewer.do?id=00000000-0000-0000-0000-000000000001"))).isFalse();}
    @ParameterizedTest @ValueSource(strings={"PAJU","GWANGMYEONG"})
    void bodyTitleAndBudget(String group){var s=CapitalEighthDownloadCases.selectCase(group);var p=Jsoup.parse(page(group,item(group,1,"hwp")));assertThat(CapitalEighthNoticePage.selectContent(Site.valueOf(group),p).text()).isEqualTo("소상공인 지원금");AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(p,"소상공인 지원",s.titleLayout());assertThatThrownBy(()->CapitalEighthNoticePage.selectContent(Site.valueOf(group),Jsoup.parse(p.toString()+p))).isInstanceOf(IllegalArgumentException.class);var budget=new AnnouncementAttachmentBbsOfficialObservationTest.Budget(s.profile(),false);assertThat(budget.maximumRequests).isEqualTo(6);assertThat(budget.maximumBytes).isEqualTo(23L*1024*1024);}
    @EnabledIfEnvironmentVariable(named="SANEB_CAPITAL_EIGHTH_SURVEY_FIXTURE",matches="true")
    @ParameterizedTest @ValueSource(strings={"PAJU","GWANGMYEONG"})
    void actualHtmlContract(String group)throws Exception{var s=CapitalEighthDownloadCases.selectCase(group);String html=Files.readString(Path.of("build/qa-capital-eighth-20260930/"+group+"-detail.html"));var p=Jsoup.parse(html);AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(p,s.title(),s.titleLayout());var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(group.equals("PAJU")?1:3).allSatisfy(d->assertThat(d.downloadAllowed()).isTrue());assertThat(CapitalEighthNoticePage.selectContent(Site.valueOf(group),p).text()).isNotBlank();}
    @ParameterizedTest @ValueSource(strings={"PAJU","GWANGMYEONG"})
    void catalogRemainsUnapproved(String group)throws Exception{var s=CapitalEighthDownloadCases.selectCase(group);var mapper=new com.fasterxml.jackson.databind.ObjectMapper();var notices=mapper.readTree(Files.readString(Path.of("src/main/resources/announcement-attachment/provider-qa-catalog-v2.json"))).path("notices");var ref=StreamSupport.stream(notices.spliterator(),false).filter(n->s.code().equals(n.path("caseCode").asText())).findFirst().orElseThrow();assertThat(ref.path("source")).isEqualTo(mapper.valueToTree(s.source()));assertThat(ref.hasNonNull("expectation")).isFalse();}
}
