package com.saneb.domain.announcementattachment.qa;
import static org.assertj.core.api.Assertions.*;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.DaejeonNextNoticePage;
import com.saneb.domain.announcementsource.provider.content.DaejeonNextNoticePage.Site;
import java.net.URI;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
class DaejeonNextDownloadContractTest {
    private String selectForm(String name,String sys,String path){return "<form id=fileForm name=fileForm method=post action=''><input type=hidden name=user_file_nm value='"+sys+"'><input type=hidden name=sys_file_nm value='"+name+"'><input type=hidden name=file_path value='"+path+"'></form>";}
    private String selectItem(String group,int id,String ext){String name="지원 공고."+ext,sys="file"+id+"."+ext,path="/ntishome/file/upload/ofr/ofr/20260910",args="'"+name+"','"+sys+"','"+path+"'";return (group.equals("YUSEONG")?"":selectForm(name,sys,path))+"<a href='"+(group.equals("YUSEONG")?"#":"#file")+"' onclick=\"fn_egov_downFile("+args+"); return false;\">"+name+"</a>"+(group.equals("YUSEONG")?"<a href='#' onclick=\"fn_egov_previewFile("+args+"); return false;\">미리보기</a>":"");}
    private String selectPage(String group,String files){return group.equals("YUSEONG")?"<div class=program--contents><div class='ui bbs--view'><div class='ui bbs--view--header'><h2 class='ui bbs--view--tit'>소상공인 지원</h2><span>수출 부서</span></div><div class='ui bbs--view--file'>"+files+"</div><div class='ui bbs--view--cont'><div class='ui bbs--detail--cont'><div class='ui bbs--view--content'>소상공인 지원금</div></div></div></div></div>"+selectForm("","",""):"<table class=table2023><tbody><tr><th class=tit00>소상공인 지원</th></tr><tr><th>부서</th><td>수출 부서</td></tr><tr><th>첨부파일</th><td>"+files+"</td></tr><tr><td class=cont_area>소상공인 지원금</td></tr></tbody></table>";}
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void preservesFilesAndSeparatesIncompleteDiscovery(String group){var s=DaejeonNextDownloadCases.selectCase(group);var p=s.profile();String files=selectItem(group,1,"pdf")+selectItem(group,2,"hwp")+selectItem(group,3,"hwpx");var r=p.selectDescriptors(s.source(),selectPage(group,files));assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(3).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(p.selectApprovedRequest(d.selectRequest(),d.selectRequest())).isTrue();assertThat(d.selectRequest().method()).isEqualTo("POST");});for(String extra:List.of("<a href='/unknown'>파일</a>","<button>파일</button>","<img src='/unknown'>")){var partial=p.selectDescriptors(s.source(),selectPage(group,files+extra));assertThat(partial.complete()).isFalse();assertThat(partial.descriptors()).hasSize(3);}var unsupported=p.selectDescriptors(s.source(),selectPage(group,files+selectItem(group,4,"xlsx")));assertThat(unsupported.complete()).isTrue();assertThat(unsupported.descriptors().getLast().downloadAllowed()).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,"")).status()).isEqualTo("NO_FILES");assertThat(p.selectDescriptors(s.source(),"<p>첨부 없음</p>").complete()).isFalse();var limit=p.selectDescriptors(s.source(),selectPage(group,IntStream.rangeClosed(1,11).mapToObj(i->selectItem(group,i,"pdf")).collect(Collectors.joining())));assertThat(limit.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(limit.descriptors()).hasSize(10);}
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void rejectsForeignHostsRedirectAndConflictingIdentity(String group){var s=DaejeonNextDownloadCases.selectCase(group);var p=s.profile();var b=p.selectSourceBindings().getFirst();String one=selectItem(group,1,"pdf");var d=p.selectDescriptors(s.source(),selectPage(group,one)).descriptors().getFirst();for(String bad:List.of(d.fetchUri().toString().replace("https:","http:"),d.fetchUri().toString().replace(d.fetchUri().getHost(),"evil.example"),d.fetchUri()+"?extra=1",d.fetchUri()+"#x",d.fetchUri().toString().replace(d.fetchUri().getHost(),"127.0.0.1"))){var request=new Request(URI.create(bad),"POST",d.postForm());assertThat(p.selectApprovedRequest(request)).isFalse();assertThat(p.selectApprovedRequest(d.selectRequest(),request)).isFalse();}assertThat(p.selectApprovedRequest(URI.create("https:opaque"))).isFalse();assertThat(p.selectApprovedRequest(Request.selectGet(d.fetchUri()))).isFalse();var n=new AnnouncementSourceIdentityNormalizer();for(String bad:List.of(s.source().sourceUrl()+"&extra=1",s.source().sourceUrl()+"&"+Site.valueOf(group).idKey+"=99",s.source().sourceUrl().replace("https:","http:")))assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",n.hash(n.canonicalizeUrl(bad)),bad,b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE","wrong",s.source().sourceUrl(),b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");var other=p.selectDescriptors(s.source(),selectPage(group,selectItem(group,2,"pdf"))).descriptors().getFirst();assertThat(p.selectApprovedRequest(d.selectRequest(),other.selectRequest())).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,one+one)).descriptors()).hasSize(1);assertThat(p.selectDescriptors(s.source(),selectPage(group,one+one.replace("지원 공고","다른 공고"))).complete()).isFalse();var budget=new AnnouncementAttachmentBbsOfficialObservationTest.Budget(p,false);assertThat(budget.maximumRequests).isEqualTo(group.equals("YUSEONG")?7:6);assertThat(budget.maximumBytes).isEqualTo((group.equals("YUSEONG")?26L:23L)*1024*1024);assertThat(AttachmentDetailLimitProfile.selectBoundedDetailMaximumBytes(p)).isEqualTo((group.equals("YUSEONG")?2L:1L)*1024*1024);}
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void formAndLiteralArgumentsCannotExecuteOtherActions(String group){var s=DaejeonNextDownloadCases.selectCase(group);String one=selectItem(group,1,"pdf");for(String bad:List.of(one.replace("fn_egov_downFile(","evil();fn_egov_downFile("),one.replace("/ntishome/","/../ntishome/"))){var r=s.profile().selectDescriptors(s.source(),selectPage(group,selectItem(group,2,"hwp")+bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}for(String bad:List.of(selectPage(group,one).replace("action=''","action='https://evil.example'"),selectPage(group,one).replace("name=file_path","name=other"),selectPage(group,one).replace("method=post","method=get")))assertThat(s.profile().selectDescriptors(s.source(),bad).complete()).isFalse();if(group.equals("YUSEONG"))assertThat(s.profile().selectDescriptors(s.source(),selectPage(group,one.replace("fn_egov_previewFile('지원 공고.pdf','file1","fn_egov_previewFile('지원 공고.pdf','file99"))).complete()).isFalse();}
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void titleBodyAndDuplicateRootBoundaries(String group){var s=DaejeonNextDownloadCases.selectCase(group);var page=Jsoup.parse(selectPage(group,selectItem(group,1,"pdf")));assertThat(DaejeonNextNoticePage.selectContent(Site.valueOf(group),page).text()).isEqualTo("소상공인 지원금");AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"소상공인 지원",s.titleLayout());assertThatThrownBy(()->DaejeonNextNoticePage.selectContent(Site.valueOf(group),Jsoup.parse(page.toString()+page))).isInstanceOf(IllegalArgumentException.class);}
    @EnabledIfEnvironmentVariable(named="SANEB_DAEJEON_NEXT_SURVEY_FIXTURE",matches="true")
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void actualHtmlBoundaries(String group)throws Exception{var s=DaejeonNextDownloadCases.selectCase(group);String html=Files.readString(Path.of("build/qa-daejeon-next-20260930/"+(group.equals("YUSEONG")?"YUSEONG-housing-detail":"DAEDEOK-detail")+".html"));var page=Jsoup.parse(html);AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,s.title(),s.titleLayout());var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).as("%s %s files=%s",r.status(),r.warnings(),r.descriptors().size()).isTrue();assertThat(r.descriptors()).hasSize(group.equals("YUSEONG")?4:3).allSatisfy(d->assertThat(d.downloadAllowed()).isTrue());assertThat(DaejeonNextNoticePage.selectContent(Site.valueOf(group),page).text()).isNotBlank();}
    @ParameterizedTest @ValueSource(strings={"YUSEONG","DAEDEOK"})
    void catalogDoesNotApproveExpectation(String group)throws Exception{var s=DaejeonNextDownloadCases.selectCase(group);var json=new com.fasterxml.jackson.databind.ObjectMapper();var notices=json.readTree(Files.readString(Path.of("src/main/resources/announcement-attachment/provider-qa-catalog-v2.json"))).path("notices");var ref=StreamSupport.stream(notices.spliterator(),false).filter(n->s.code().equals(n.path("caseCode").asText())).findFirst().orElseThrow();assertThat(ref.path("source")).isEqualTo(json.valueToTree(s.source()));assertThat(ref.hasNonNull("expectation")).isFalse();assertThat(s.expectedTitleStopStage()).isEqualTo(group.equals("YUSEONG")?com.saneb.domain.announcementsource.classification.AnnouncementSourceClassificationCodes.TitleStageCode.COMBINATION_NOT_MATCHED:null);}
}
