package com.saneb.domain.announcementattachment.qa;

import static org.assertj.core.api.Assertions.*;
import java.net.URI;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import com.saneb.domain.announcementattachment.discovery.AttachmentDiscoveryProfile;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.classification.*;

class GeojeDownloadContractTest {
    private final AnnouncementAttachmentBbsOfficialObservationTest.ObservationCase sample=GeojeDownloadCases.selectCase();
    private String selectItem(int id,String ext){return "<a class=atta href=\"javascript:goDownLoad('지원 공고 "+id+"."+ext+"','stored_"+id+"."+ext+"','/ntishome/file/upload/ofr/ofr/20260209')\"><span>지원 공고 "+id+"."+ext+"</span></a>";}
    private String selectPreview(int index,String ext){return "<a href='/synap/skin/doc.html?fn=67219"+index+"."+ext+"&rs=/upload_data/Synap/gosi_/' target=_blank><img alt='바로보기' src='/images/ic_2.gif'></a>";}
    private String selectPage(String items){return "<div class=board-view><div class=view01><div class=title>"+sample.title()+"</div><div class=info>담당부서</div><div class=attach>"+items+"</div><div class=substan>소상공인 지원</div><div><iframe src='/synap/skin/doc.html'></iframe></div></div></div>";}
    @Test void boundedBudgetDoesNotAddHeaderOrMimeExceptions(){var b=AnnouncementAttachmentBbsOfficialObservationTest.selectBudget(sample.profile(),true,false);assertThat(b.maximumRequests).isEqualTo(6);assertThat(b.maximumBytes).isEqualTo(23*1024*1024);assertThat(sample.profile().selectLegacyBinaryContentTypes()).isEmpty();assertThat(sample.profile().selectUtf8DispositionOctets()).isFalse();}
    @Test void officialArgumentsProduceLgaDownloadNotPreviewOrScriptExecution(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp")+selectPreview(0,"hwp")+"<br>"+selectItem(2,"pdf")+selectPreview(1,"pdf")));assertThat(r.status()).isEqualTo("FOUND");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(2).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(d.postForm()).isEmpty();assertThat(d.fetchUri().getPath()).isEqualTo("/emwp/jsp/lga/homepage/FileDown.jsp");assertThat(sample.profile().selectApprovedRequest(d.fetchUri())).isTrue();assertThat(d.toString()).doesNotContain("공고","https");});}
    @Test void unknownLinksUnsupportedFilesAndWrongPreviewPreserveGoodFiles(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp")+selectPreview(9,"hwp")+selectItem(2,"xlsx")+"<a href='/unknown'>미확인</a>"));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(2);assertThat(r.descriptors().getFirst().downloadAllowed()).isTrue();assertThat(r.descriptors().getLast().downloadAllowed()).isFalse();}
    @Test void detectsMissingChangedDuplicateAndLimitedAttachments(){var p=sample.profile();assertThat(p.selectDescriptors(sample.source(),selectPage("")).status()).isEqualTo("NO_FILES");for(String bad:List.of("<html>오류</html>",selectPage("<p>알 수 없음</p>"),selectPage("")+selectPage(""),selectPage("").replace("class=attach","class=other")))assertThat(p.selectDescriptors(sample.source(),bad).complete()).isFalse();var r=p.selectDescriptors(sample.source(),selectPage(IntStream.rangeClosed(1,11).mapToObj(i->selectItem(i,"pdf")).collect(Collectors.joining())));assertThat(r.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(r.descriptors()).hasSize(10);String item=selectItem(1,"hwp");assertThat(p.selectDescriptors(sample.source(),selectPage(item+item)).descriptors()).hasSize(1);}
    @Test void titleSourceIdentityAndTitlePolicyRemainRequired()throws Exception{var p=sample.profile();var s=sample.source();assertThat(p.selectDetailUri(s).toString()).isEqualTo(s.sourceUrl());assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source(s.providerCode(),s.providerNoticeId(),s.sourceUrl(),"LGS-000001",s.listParserProfileCode()))).isInstanceOf(IllegalArgumentException.class);var page=Jsoup.parse(selectPage(selectItem(1,"hwp")));AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,sample.title(),sample.titleLayout());assertThatThrownBy(()->AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"다른 제목",sample.titleLayout())).isInstanceOf(AssertionError.class);var d=new AnnouncementSourceClassificationEngine().selectDecision(new AnnouncementSourceClassificationInput("LOCAL_GOV_NOTICE",sample.title(),null,null,List.of(),AnnouncementSourceClassificationCodes.BodySourceCode.NONE,AnnouncementSourceClassificationCodes.BodyAvailabilityCode.UNAVAILABLE),AnnouncementAttachmentRealFileQaTest.selectDraftRuleSet());assertThat(AnnouncementAttachmentBbsOfficialObservationTest.selectTitleMayProceed(d)).isTrue();}
    @Test void knownListSearchFieldsDoNotBecomeDetailRequestParameters(){var s=sample.source();var n=new AnnouncementSourceIdentityNormalizer();String url=s.sourceUrl()+"&startPage=2&searchType=NOT_ANCMT_SJ&keyword=&DEP_NM=&NOT_ANCMT_SJ=&NOT_ANCMT_CN=";var source=new AttachmentDiscoveryProfile.Source(s.providerCode(),n.hash(n.canonicalizeUrl(url)),url,s.localSourceCode(),s.listParserProfileCode());assertThat(sample.profile().selectDetailUri(source).toString()).isEqualTo(s.sourceUrl());}
    @Test void boardQueryPostHostAndRedirectAreRestricted(){var p=sample.profile();var detail=p.selectDetailUri(sample.source());var file=p.selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp"))).descriptors().getFirst().fetchUri();for(String bad:List.of(detail+"&idx=2",detail+"&extra=x",detail.toString().replace("DOM_000008902001002001","DOM_000008902001002002"),detail.toString().replace("https:","http:"),detail.toString().replace("m=D","m=L"),file+"&extra=x",file.toString().replace("eminwon.geoje.go.kr","evil.go.kr"),file.toString().replace("/lga/homepage/","/ofr/")))assertThat(p.selectApprovedRequest(URI.create(bad))).isFalse();assertThat(p.selectApprovedRequest(new Request(file,"POST",Map.of("x","y")))).isFalse();assertThat(p.selectApprovedRequest(Request.selectGet(detail),Request.selectGet(file))).isFalse();}
    @Test void invalidInvocationAndActiveContentDoNotDiscardOtherFiles(){String item=selectItem(1,"hwp");for(String bad:List.of(item.replace("javascript:goDownLoad(","javascript:evil();goDownLoad("),item.replace("/20260209","/../private"),item.replace("<a class=atta","<a onclick='x()' class=atta"),item.replace("<span>지원 공고 1.hwp</span>","<span>다른 이름</span>"))){var r=sample.profile().selectDescriptors(sample.source(),selectPage(bad+selectItem(2,"hwp")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}}
    @Test void onlyOfficialAttachmentAreaIsUsed(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp"))+"<a href='/unrelated.pdf'>메뉴 파일</a>");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(1);}
}
