package com.saneb.domain.announcementattachment.qa;
import static org.assertj.core.api.Assertions.*;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.IncheonThirdNoticePage;
import com.saneb.domain.announcementsource.provider.content.IncheonThirdNoticePage.Site;
import java.net.URI;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
class IncheonThirdDownloadContractTest {
    private String selectItem(String group,int id,String ext){String name="지원 공고."+ext;
        if(group.equals("GEOMDAN")){String q="bcd=notice&msg_seq=235&fileno="+id,url="/main/bbs/bbsMsgFileDown.do?"+q;return "<li><p class=tit><a href='"+url+"'>"+name+"</a><span class=margin_l10>[45.3KByte]</span></p><div class=btn-wrap><button onclick=\"location.href='"+url+"'\">다운로드</button><button onclick=\"window.open('/main/bbs/bbsMsgFileView.do?"+q+"', '_blank')\">미리보기</button></div></li>";}
        return "<li><div class=file_box><div class=file_name><span>"+name+" ["+ext+", 0.06MB]</span></div><div class=file_btns><a href='/other/synap_viewer/view.do?atch_file_sn="+id+"'>미리보기</a><a download href='/other/attach/process.file.do?TP=dn&sn="+id+"&key=000000000000000'><span><span class=skip>"+name+"</span>다운로드</span></a></div></div></li>";
    }
    private String selectPage(String group,String files){return group.equals("GEOMDAN")?"<div class=board-view><div class=title>소상공인 지원</div><ul class=info-data><li>수출 부서</li><li class=attach-file><dl><dt>첨부파일</dt><dd><ul>"+files+"</ul></dd></dl></li></ul><div class=con-box><div class=detail>소상공인 지원금</div></div></div>":"<div class=cm_board_detail1><div class=board_header_wrap><div class=board_header><div class=board_title>소상공인 지원</div></div><div>수출 부서</div></div><div class=board_content><div class=editor_content>소상공인 지원금</div></div><ul class=cm_file_list2>"+files+"</ul></div>";}
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void preservesGoodFilesAndRecordsOtherFailures(String group){var s=IncheonThirdDownloadCases.selectCase(group);var p=s.profile();String files=selectItem(group,1,"pdf")+selectItem(group,2,"hwp")+selectItem(group,3,"hwpx");var r=p.selectDescriptors(s.source(),selectPage(group,files));assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(3).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(p.selectApprovedRequest(d.selectRequest(),d.selectRequest())).isTrue();assertThat(d.locator().toString()).doesNotContain("key=","지원 공고");});
        for(String extra:List.of("<a href='/unknown'>파일</a>","<button>파일</button>","<img src='/unknown'>")){var partial=p.selectDescriptors(s.source(),selectPage(group,files+extra));assertThat(partial.complete()).isFalse();assertThat(partial.descriptors()).hasSize(3);}
        var unsupported=p.selectDescriptors(s.source(),selectPage(group,files+selectItem(group,4,"xlsx")));assertThat(unsupported.complete()).isTrue();assertThat(unsupported.descriptors().getLast().downloadAllowed()).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,"")).status()).isEqualTo("NO_FILES");assertThat(p.selectDescriptors(s.source(),"<p>첨부 없음</p>").complete()).isFalse();var limit=p.selectDescriptors(s.source(),selectPage(group,IntStream.rangeClosed(1,11).mapToObj(i->selectItem(group,i,"pdf")).collect(Collectors.joining())));assertThat(limit.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(limit.descriptors()).hasSize(10);
    }
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void sourceRequestRedirectAndDuplicateBoundaries(String group){var s=IncheonThirdDownloadCases.selectCase(group);var p=s.profile();var b=p.selectSourceBindings().getFirst();String one=selectItem(group,1,"pdf");var d=p.selectDescriptors(s.source(),selectPage(group,one)).descriptors().getFirst();
        for(String bad:List.of(d.fetchUri().toString().replace("https:","http:"),d.fetchUri().toString().replace(d.fetchUri().getHost(),"evil.example"),d.fetchUri()+"&extra=1",d.fetchUri()+"#x",d.fetchUri().toString().replace(d.fetchUri().getHost(),"127.0.0.1"))){assertThat(p.selectApprovedRequest(URI.create(bad))).isFalse();assertThat(p.selectApprovedRequest(d.selectRequest(),Request.selectGet(URI.create(bad)))).isFalse();}
        assertThat(p.selectApprovedRequest(URI.create("https:opaque"))).isFalse();assertThat(p.selectApprovedRequest(new Request(d.fetchUri(),"POST",Map.of("x","1")))).isFalse();var n=new AnnouncementSourceIdentityNormalizer();for(String bad:List.of(s.source().sourceUrl()+"&extra=1",s.source().sourceUrl()+"&"+Site.valueOf(group).idKey+"=99",s.source().sourceUrl().replace("https:","http:")))assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",n.hash(n.canonicalizeUrl(bad)),bad,b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");
        assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE","wrong",s.source().sourceUrl(),b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",s.source().providerNoticeId(),s.source().sourceUrl(),"LGS-OTHER",b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");var other=p.selectDescriptors(s.source(),selectPage(group,selectItem(group,2,"pdf"))).descriptors().getFirst();assertThat(p.selectApprovedRequest(d.selectRequest(),other.selectRequest())).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,one+one)).descriptors()).hasSize(1);var conflict=p.selectDescriptors(s.source(),selectPage(group,one+one.replace("지원 공고","다른 공고")));assertThat(conflict.complete()).isFalse();assertThat(conflict.descriptors()).hasSize(1);var budget=new AnnouncementAttachmentBbsOfficialObservationTest.Budget(p,false);assertThat(budget.maximumRequests).isEqualTo(6);assertThat(budget.maximumBytes).isEqualTo(23L*1024*1024);
    }
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void ignoresOnlySameFilePreviewAndRejectsOtherDownloadIdentity(String group){var s=IncheonThirdDownloadCases.selectCase(group);String one=selectItem(group,1,"hwpx"),bad=group.equals("GEOMDAN")?one.replace("bbsMsgFileView.do?bcd=notice&msg_seq=235","bbsMsgFileView.do?bcd=notice&msg_seq=99"):one.replace("atch_file_sn=1","atch_file_sn=99");var r=s.profile().selectDescriptors(s.source(),selectPage(group,bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);String invalid=group.equals("GEOMDAN")?one.replace("msg_seq=235","msg_seq=99"):one.replace("TP=dn","TP=upload");assertThat(s.profile().selectDescriptors(s.source(),selectPage(group,invalid)).descriptors()).isEmpty();String preview=group.equals("GEOMDAN")?"/main/bbs/bbsMsgFileView.do?bcd=notice&msg_seq=235&fileno=1":"/other/synap_viewer/view.do?atch_file_sn=1";assertThat(s.profile().selectApprovedRequest(URI.create("https://"+Site.valueOf(group).host+preview))).isFalse();}
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void selectsBodyTitleAndRejectsAmbiguousRoots(String group){var s=IncheonThirdDownloadCases.selectCase(group);var page=Jsoup.parse(selectPage(group,selectItem(group,1,"pdf")));assertThat(IncheonThirdNoticePage.selectContent(Site.valueOf(group),page).text()).isEqualTo("소상공인 지원금");AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"소상공인 지원",s.titleLayout());assertThatThrownBy(()->IncheonThirdNoticePage.selectContent(Site.valueOf(group),Jsoup.parse(page.toString()+page))).isInstanceOf(IllegalArgumentException.class);}
    @EnabledIfEnvironmentVariable(named="SANEB_INCHEON_THIRD_SURVEY_FIXTURE",matches="true")
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void actualOfficialHtmlBoundaries(String group)throws Exception{var s=IncheonThirdDownloadCases.selectCase(group);String html=Files.readString(Path.of("build/qa-incheon-third-20260930/"+group+"-detail.html"));var page=Jsoup.parse(html);AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,s.title(),s.titleLayout());var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).as("%s %s files=%s",r.status(),r.warnings(),r.descriptors().size()).isTrue();assertThat(r.descriptors()).hasSize(1).allSatisfy(d->assertThat(d.downloadAllowed()).isTrue());assertThat(IncheonThirdNoticePage.selectContent(Site.valueOf(group),page).text()).isNotBlank();}
    @ParameterizedTest @ValueSource(strings={"GEOMDAN","YEONGJONG"})
    void catalogHasNoApprovedExpectation(String group)throws Exception{var s=IncheonThirdDownloadCases.selectCase(group);var json=new com.fasterxml.jackson.databind.ObjectMapper();var notices=json.readTree(Files.readString(Path.of("src/main/resources/announcement-attachment/provider-qa-catalog-v2.json"))).path("notices");var ref=StreamSupport.stream(notices.spliterator(),false).filter(n->s.code().equals(n.path("caseCode").asText())).findFirst().orElseThrow();assertThat(ref.path("source")).isEqualTo(json.valueToTree(s.source()));assertThat(ref.hasNonNull("expectation")).isFalse();}
}
