package com.saneb.domain.announcementattachment.qa;

import static org.assertj.core.api.Assertions.*;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.IncheonSecondNoticePage;
import com.saneb.domain.announcementsource.provider.content.IncheonSecondNoticePage.Site;
import java.net.URI;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class IncheonSecondDownloadContractTest {
    private String selectItem(String group,int id,String ext){String name="지원 공고."+ext;if(group.equals("JEMULPO")){String q="bcd=announce&msg_seq=14094&fileno="+id,url="/main/bbs/bbsMsgFileDown.do?"+q;return "<li><p class=tit><a href='"+url+"'>"+name+"</a><span class=margin_l10>[68.5KByte]</span></p><div class=btn-wrap><button onclick=\"location.href='"+url+"'\">다운로드</button><button onclick=\"window.open('/main/bbs/bbsMsgFileView.do?"+q+"', '_blank')\">미리보기</button></div></li>";}
        return "<a href=\"javascript:fnFileDown('https://eminwon.michuhol.go.kr/emwp/jsp/ofr/FileDownNew.jsp','원문 "+"A".repeat(40)+id+"','저장 "+"B".repeat(40)+id+"','/ntisho"+"C".repeat(50)+"','"+name+"')\">"+name+"</a><br>";
    }
    private String selectForm(){return "<form id=formCrawling name=formCrawling method=post action='/other/crawling_file_down.do'>"+Stream.of("downloadUrl","userFileNm","sysFileNm","filePath","fileOrigin").map(n->"<input type=hidden name="+n+" value=''>").collect(Collectors.joining())+"</form>";}
    private String selectPage(String group,String files){return group.equals("JEMULPO")?"<div class=board-view><div class=title>소상공인 지원</div><ul class=info-data><li><dl><dt>부서</dt><dd>수출 메타데이터</dd></dl></li><li class=attach-file><dl><dt>첨부파일</dt><dd><ul>"+files+"</ul><a class=alldown href='/main/bbs/bbsMsgFileDownCompress.do?bcd=announce&msg_seq=14094'>전체다운</a></dd></dl></li></ul><div class=con-box><div class=detail>소상공인 지원금</div></div></div>":"<div class=board-view-s1><h3 class=board-title>소상공인 지원</h3><div class=category-area>수출 부서</div><div class='file-area file-crawling'>"+files+"</div><div class='content editor_content'><div class='content editor_content'>소상공인 지원금</div></div></div>"+selectForm();}
    @ParameterizedTest @ValueSource(strings={"JEMULPO","MICHUHOL"})
    void keepsGoodFilesAndUnsupportedSeparateFromOtherErrors(String group){var s=IncheonSecondDownloadCases.selectCase(group);var p=s.profile();String files=selectItem(group,1,"pdf")+selectItem(group,2,"hwp")+selectItem(group,3,"hwpx");var r=p.selectDescriptors(s.source(),selectPage(group,files));assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(3);r.descriptors().forEach(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(d.selectRequest().method()).isEqualTo(group.equals("JEMULPO")?"GET":"POST");assertThat(p.selectApprovedRequest(d.selectRequest(),d.selectRequest())).isTrue();assertThat(d.locator().toString()).doesNotContain("원문","저장","ntisho");});
        for(String extra:List.of("<a href='/unknown'>첨부</a>","<button>파일</button>","<img src='/unknown'>")){var partial=p.selectDescriptors(s.source(),selectPage(group,files+extra));assertThat(partial.complete()).isFalse();assertThat(partial.descriptors()).hasSize(3);}
        var unsupported=p.selectDescriptors(s.source(),selectPage(group,files+selectItem(group,4,"docx")));assertThat(unsupported.complete()).isTrue();assertThat(unsupported.descriptors().getLast().downloadAllowed()).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,"")).status()).isEqualTo("NO_FILES");assertThat(p.selectDescriptors(s.source(),"<p>첨부 없음</p>").complete()).isFalse();
        var limit=p.selectDescriptors(s.source(),selectPage(group,IntStream.rangeClosed(1,11).mapToObj(i->selectItem(group,i,"pdf")).collect(Collectors.joining())));assertThat(limit.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(limit.descriptors()).hasSize(10);
    }
    @ParameterizedTest @ValueSource(strings={"JEMULPO","MICHUHOL"})
    void bindsSourceAndRequestWithoutForeignHostOrRedirect(String group){var s=IncheonSecondDownloadCases.selectCase(group);var p=s.profile();var b=p.selectSourceBindings().getFirst();String one=selectItem(group,1,"pdf");var d=p.selectDescriptors(s.source(),selectPage(group,one)).descriptors().getFirst();
        for(String bad:List.of(d.fetchUri().toString().replace("https:","http:"),d.fetchUri().toString().replace(d.fetchUri().getHost(),"evil.example"),d.fetchUri()+"?extra=1",d.fetchUri()+"#x",d.fetchUri().toString().replace(d.fetchUri().getHost(),"127.0.0.1"))){var next=new Request(URI.create(bad),d.selectRequest().method(),d.selectRequest().form());assertThat(p.selectApprovedRequest(next)).isFalse();assertThat(p.selectApprovedRequest(d.selectRequest(),next)).isFalse();}
        assertThat(p.selectApprovedRequest(URI.create("https:opaque"))).isFalse();var n=new AnnouncementSourceIdentityNormalizer();for(String bad:List.of(s.source().sourceUrl()+"&extra=1",s.source().sourceUrl()+"&"+Site.valueOf(group).idKey+"=99",s.source().sourceUrl().replace("https:","http:")))assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",n.hash(n.canonicalizeUrl(bad)),bad,b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");
        assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE","wrong",s.source().sourceUrl(),b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",s.source().providerNoticeId(),s.source().sourceUrl(),"LGS-OTHER",b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");
        var other=p.selectDescriptors(s.source(),selectPage(group,selectItem(group,2,"pdf"))).descriptors().getFirst();assertThat(p.selectApprovedRequest(d.selectRequest(),other.selectRequest())).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,one+one)).descriptors()).hasSize(1);var conflict=p.selectDescriptors(s.source(),selectPage(group,one+one.replace("지원 공고","다른 공고")));assertThat(conflict.complete()).isFalse();assertThat(conflict.descriptors()).hasSize(1);var budget=new AnnouncementAttachmentBbsOfficialObservationTest.Budget(p,false);assertThat(budget.maximumRequests).isEqualTo(6);assertThat(budget.maximumBytes).isEqualTo(23L*1024*1024);
    }
    @Test void michuholProxyDestinationAndFiveLiteralArgumentsAreFixed(){var s=IncheonSecondDownloadCases.selectCase("MICHUHOL");var p=s.profile();String one=selectItem("MICHUHOL",1,"hwpx");for(String bad:List.of(one.replace("https://eminwon.michuhol.go.kr","http://127.0.0.1"),one.replace("javascript:fnFileDown(","javascript:evil();fnFileDown("),one.replace("','지원 공고.hwpx')","','다른 공고.hwpx')"),one.replace("')\">", "');evil()\">"),one.replace("/ntisho","/../ntisho"))){var r=p.selectDescriptors(s.source(),selectPage("MICHUHOL",selectItem("MICHUHOL",2,"pdf")+bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}
        assertThat(p.selectDescriptors(s.source(),selectPage("MICHUHOL",one).replace("method=post","method=get")).warnings()).contains("ATTACHMENT_DOWNLOAD_FORM_CHANGED");assertThat(p.selectDescriptors(s.source(),selectPage("MICHUHOL",one).replace("name=fileOrigin","name=other")).complete()).isFalse();var d=p.selectDescriptors(s.source(),selectPage("MICHUHOL",one)).descriptors().getFirst();assertThat(p.selectApprovedRequest(Request.selectGet(d.fetchUri()))).isFalse();var f=new HashMap<>(d.postForm());f.put("downloadUrl","https://evil.example/file");assertThat(p.selectApprovedRequest(new Request(d.fetchUri(),"POST",f))).isFalse();}
    @Test void jemulpoPreviewAndBulkNeverAuthorizeDownloads(){var s=IncheonSecondDownloadCases.selectCase("JEMULPO");String one=selectItem("JEMULPO",1,"pdf");for(String bad:List.of(one.replace("window.open('/main/bbs/bbsMsgFileView.do?bcd=announce&msg_seq=14094","window.open('/main/bbs/bbsMsgFileView.do?bcd=announce&msg_seq=99"),one.replace("location.href=","evil();location.href="))){var r=s.profile().selectDescriptors(s.source(),selectPage("JEMULPO",bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}assertThat(s.profile().selectApprovedRequest(URI.create("https://www.jemulpo.go.kr/main/bbs/bbsMsgFileDownCompress.do?bcd=announce&msg_seq=14094"))).isFalse();assertThat(s.profile().selectDescriptors(s.source(),selectPage("JEMULPO",one.replace("msg_seq=14094","msg_seq=99"))).descriptors()).isEmpty();}
    @ParameterizedTest @ValueSource(strings={"JEMULPO","MICHUHOL"})
    void selectsOnlyOfficialBodyAndTitle(String group){var s=IncheonSecondDownloadCases.selectCase(group);var page=Jsoup.parse(selectPage(group,selectItem(group,1,"pdf")));assertThat(IncheonSecondNoticePage.selectContent(Site.valueOf(group),page).text()).isEqualTo("소상공인 지원금");AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"소상공인 지원",s.titleLayout());assertThatThrownBy(()->IncheonSecondNoticePage.selectContent(Site.valueOf(group),Jsoup.parse(page.toString()+page))).isInstanceOf(IllegalArgumentException.class);}
    @EnabledIfEnvironmentVariable(named="SANEB_INCHEON_SECOND_SURVEY_FIXTURE",matches="true")
    @ParameterizedTest @ValueSource(strings={"JEMULPO","MICHUHOL"})
    void officialHtmlBoundaries(String group)throws Exception{var s=IncheonSecondDownloadCases.selectCase(group);String html=Files.readString(Path.of("build/qa-incheon-second-20260930/"+group+"-detail.html"));var page=Jsoup.parse(html);AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,s.title(),s.titleLayout());var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).as("%s %s files=%s",r.status(),r.warnings(),r.descriptors().size()).isTrue();assertThat(r.descriptors()).hasSize(3).allSatisfy(d->assertThat(d.downloadAllowed()).isTrue());assertThat(IncheonSecondNoticePage.selectContent(Site.valueOf(group),page).text()).isNotBlank();}
    @ParameterizedTest @ValueSource(strings={"JEMULPO","MICHUHOL"})
    void catalogReferencesAreNotApproved(String group)throws Exception{var s=IncheonSecondDownloadCases.selectCase(group);var json=new com.fasterxml.jackson.databind.ObjectMapper();var notices=json.readTree(Files.readString(Path.of("src/main/resources/announcement-attachment/provider-qa-catalog-v2.json"))).path("notices");var ref=StreamSupport.stream(notices.spliterator(),false).filter(n->s.code().equals(n.path("caseCode").asText())).findFirst().orElseThrow();assertThat(ref.path("source")).isEqualTo(json.valueToTree(s.source()));assertThat(ref.hasNonNull("expectation")).isFalse();}
}
