package com.saneb.domain.announcementattachment.qa;
import static org.assertj.core.api.Assertions.*;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.MetroNextNoticePage;
import com.saneb.domain.announcementsource.provider.content.MetroNextNoticePage.Site;
import java.net.URI;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
class MetroNextDownloadContractTest {
    private String selectItem(String group,int id,String ext){String name="지원 공고."+ext,args="'"+name+"','file"+id+"."+ext+"','/ntishome/file/upload/ofr/ofr/20260910'";return group.equals("GWANGJU_NAMGU")?"<a href=\"javascript:goDownLoad("+args+")\">"+name+"</a>":"<a href=\"javascript:fn_egov_downFile("+args+");\"><i class='ir ir-bbs ir-file left ir-hwp'></i>"+name+"</a><a href=\"javascript:fn_egov_preview_File("+args+");\"><i class='ir ir-bbs ir-file left ir-view'></i>미리보기</a>";}
    private String selectPage(String group,String files){return group.equals("GWANGJU_NAMGU")?"<form name=form1 method=post><div class=tstyle_view><div class=title>청년 지원</div><ul class=head><li>수출 부서</li></ul><div class=tb_contents>청년 지원금</div><div class=add_file><strong>첨부파일</strong><div>"+files+"</div></div></div></form>":"<div class=program--contents><div class='ui bbs--view'><div class='ui bbs--view--header'><h2 class='ui bbs--view--tit'>청년 지원</h2><span>수출 부서</span></div><div class='ui bbs--view--file'>"+files+"</div><div class='ui bbs--view--cont'><div class='ui bbs--detail--cont'><div class='ui bbs--view--content'>청년 지원금</div></div></div></div></div><form id=fileForm name=fileForm method=post action='https://eminwon.djjunggu.go.kr/emwp/jsp/ofr/FileDown.jsp'><input type=hidden name=user_file_nm><input type=hidden name=sys_file_nm><input type=hidden name=file_path></form>";}
    @ParameterizedTest @ValueSource(strings={"GWANGJU_NAMGU","DAEJEON_JUNGGU"})
    void preservesSuccessfulDescriptorsAndSeparatesFailures(String group){var s=MetroNextDownloadCases.selectCase(group);var p=s.profile();String files=selectItem(group,1,"pdf")+selectItem(group,2,"hwp")+selectItem(group,3,"hwpx");var r=p.selectDescriptors(s.source(),selectPage(group,files));assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(3).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(p.selectApprovedRequest(d.selectRequest(),d.selectRequest())).isTrue();});for(String extra:List.of("<a href='/unknown'>파일</a>","<button>파일</button>","<img src='/unknown'>")){var partial=p.selectDescriptors(s.source(),selectPage(group,files+extra));assertThat(partial.complete()).isFalse();assertThat(partial.descriptors()).hasSize(3);}var unsupported=p.selectDescriptors(s.source(),selectPage(group,files+selectItem(group,4,"xlsx")));assertThat(unsupported.complete()).isTrue();assertThat(unsupported.descriptors().getLast().downloadAllowed()).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,"")).status()).isEqualTo("NO_FILES");assertThat(p.selectDescriptors(s.source(),"<p>첨부 없음</p>").complete()).isFalse();var limit=p.selectDescriptors(s.source(),selectPage(group,IntStream.rangeClosed(1,11).mapToObj(i->selectItem(group,i,"pdf")).collect(Collectors.joining())));assertThat(limit.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(limit.descriptors()).hasSize(10);}
    @ParameterizedTest @ValueSource(strings={"GWANGJU_NAMGU","DAEJEON_JUNGGU"})
    void rejectsSourceForeignHostRedirectAndConflictingDuplicates(String group){var s=MetroNextDownloadCases.selectCase(group);var p=s.profile();var b=p.selectSourceBindings().getFirst();String one=selectItem(group,1,"pdf");var d=p.selectDescriptors(s.source(),selectPage(group,one)).descriptors().getFirst();for(String bad:List.of(d.fetchUri().toString().replace("https:","http:"),d.fetchUri().toString().replace(d.fetchUri().getHost(),"evil.example"),d.fetchUri()+"?extra=1",d.fetchUri()+"#x",d.fetchUri().toString().replace(d.fetchUri().getHost(),"127.0.0.1"))){var request=new Request(URI.create(bad),d.selectRequest().method(),d.selectRequest().form());assertThat(p.selectApprovedRequest(request)).isFalse();assertThat(p.selectApprovedRequest(d.selectRequest(),request)).isFalse();}assertThat(p.selectApprovedRequest(URI.create("https:opaque"))).isFalse();var n=new AnnouncementSourceIdentityNormalizer();for(String bad:List.of(s.source().sourceUrl()+"&extra=1",s.source().sourceUrl()+"&"+Site.valueOf(group).idKey+"=99",s.source().sourceUrl().replace("https:","http:")))assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",n.hash(n.canonicalizeUrl(bad)),bad,b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE","wrong",s.source().sourceUrl(),b.localSourceCode(),b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source("LOCAL_GOV_NOTICE",s.source().providerNoticeId(),s.source().sourceUrl(),"LGS-OTHER",b.listParserProfileCode()))).hasMessage("PROFILE_REQUIRED");var other=p.selectDescriptors(s.source(),selectPage(group,selectItem(group,2,"pdf"))).descriptors().getFirst();assertThat(p.selectApprovedRequest(d.selectRequest(),other.selectRequest())).isFalse();assertThat(p.selectDescriptors(s.source(),selectPage(group,one+one)).descriptors()).hasSize(1);var conflict=p.selectDescriptors(s.source(),selectPage(group,one+one.replace("지원 공고","다른 공고")));assertThat(conflict.complete()).isFalse();var budget=new AnnouncementAttachmentBbsOfficialObservationTest.Budget(p,false);assertThat(budget.maximumRequests).isEqualTo(6);assertThat(budget.maximumBytes).isEqualTo(23L*1024*1024);}
    @Test void daejeonFileFormDestinationAndArgumentsAreFixed(){String g="DAEJEON_JUNGGU",one=selectItem(g,1,"hwpx");var s=MetroNextDownloadCases.selectCase(g);for(String page:List.of(selectPage(g,one).replace("action='https://eminwon.djjunggu.go.kr","action='https://evil.example"),selectPage(g,one).replace("name=file_path","name=other"),selectPage(g,one).replace("method=post","method=get")))assertThat(s.profile().selectDescriptors(s.source(),page).warnings()).contains("ATTACHMENT_DOWNLOAD_FORM_CHANGED");for(String bad:List.of(one.replace("fn_egov_downFile(","evil();fn_egov_downFile("),one.replace("/ntishome/","/../ntishome/"),one.replace("fn_egov_preview_File('지원 공고.hwpx','file1","fn_egov_preview_File('지원 공고.hwpx','file99"))){var r=s.profile().selectDescriptors(s.source(),selectPage(g,bad));assertThat(r.complete()).isFalse();}var d=s.profile().selectDescriptors(s.source(),selectPage(g,one)).descriptors().getFirst();assertThat(s.profile().selectApprovedRequest(Request.selectGet(d.fetchUri()))).isFalse();}
    @ParameterizedTest @ValueSource(strings={"GWANGJU_NAMGU","DAEJEON_JUNGGU"})
    void bodyTitleBoundaries(String group){var s=MetroNextDownloadCases.selectCase(group);var page=Jsoup.parse(selectPage(group,selectItem(group,1,"pdf")));assertThat(MetroNextNoticePage.selectContent(Site.valueOf(group),page).text()).isEqualTo("청년 지원금");AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"청년 지원",s.titleLayout());assertThatThrownBy(()->MetroNextNoticePage.selectContent(Site.valueOf(group),Jsoup.parse(page.toString()+page))).isInstanceOf(IllegalArgumentException.class);}
    @EnabledIfEnvironmentVariable(named="SANEB_METRO_NEXT_SURVEY_FIXTURE",matches="true")
    @ParameterizedTest @ValueSource(strings={"GWANGJU_NAMGU","DAEJEON_JUNGGU"})
    void actualHtmlBoundaries(String group)throws Exception{var s=MetroNextDownloadCases.selectCase(group);String html=Files.readString(Path.of("build/qa-metro-next-20260930/"+(group.equals("GWANGJU_NAMGU")?"GW_NAMGU":"DJ_JUNGGU")+"-detail.html"));var page=Jsoup.parse(html);AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,s.title(),s.titleLayout());var r=s.profile().selectDescriptors(s.source(),html);assertThat(r.complete()).as("%s %s",r.status(),r.warnings()).isTrue();assertThat(r.descriptors()).hasSize(group.equals("GWANGJU_NAMGU")?2:1).allSatisfy(d->assertThat(d.downloadAllowed()).isTrue());assertThat(MetroNextNoticePage.selectContent(Site.valueOf(group),page).text()).isNotBlank();}
    @ParameterizedTest @ValueSource(strings={"GWANGJU_NAMGU","DAEJEON_JUNGGU"})
    void catalogReferenceOnly(String group)throws Exception{var s=MetroNextDownloadCases.selectCase(group);var json=new com.fasterxml.jackson.databind.ObjectMapper();var notices=json.readTree(Files.readString(Path.of("src/main/resources/announcement-attachment/provider-qa-catalog-v2.json"))).path("notices");var ref=StreamSupport.stream(notices.spliterator(),false).filter(n->s.code().equals(n.path("caseCode").asText())).findFirst().orElseThrow();assertThat(ref.path("source")).isEqualTo(json.valueToTree(s.source()));assertThat(ref.hasNonNull("expectation")).isFalse();}
}
