package com.saneb.domain.announcementattachment.qa;

import static org.assertj.core.api.Assertions.*;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import com.saneb.domain.announcementattachment.discovery.*;
import com.saneb.domain.announcementattachment.worker.AttachmentFileTypeValidator;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.*;
import com.saneb.domain.announcementsource.classification.*;

class ProvinceNextDownloadContractTest {
    @TempDir Path temporary;
    private String selectFile(int id){return "https://minwon.chungnam.go.kr/citynet/jsp/cmm/attach/download.jsp?mode=download&fid=%23"+"a".repeat(64)+"&index="+id+"&other=%23"+"b".repeat(96);}
    private String selectItem(boolean gn,int id,String ext){
        String name="지원 공고 "+id+"."+ext;
        if(gn)return "<span class=attach_"+id+"><a class=file href='/index.gyeong?contentsSid=3651&fn="+URLEncoder.encode(name,StandardCharsets.UTF_8)+"'>"+name+"</a></span>";
        String file=selectFile(id);return "<li>"+name+"<a class=ico_file href='"+file+"'>내려받기</a><a class=filelist_link href='javascript:void(0);' onclick=\"previewEncodingUrlAjax('"+file+"','"+name+"')\">미리보기</a><a class=filelist_link href='javascript:void(0);' onclick=\"preListenEncodingUrlAjax('"+file+"','"+name+"')\">미리듣기</a></li>";
    }
    private String selectPage(boolean gn,String items){
        var s=ProvinceNextDownloadCases.selectCase(gn);
        return gn?"<div class='basicView view-v2'><div class=titleField><h4>"+s.title()+"</h4></div><div class=conField><ul><li><span>담당부서</span><p>수출 부서</p></li><li><span>첨부파일</span><p>"+items+"</p></li></ul></div><div class=conText>소상공인 정책자금 지원</div></div>":"<div class=board-view><div class=board-view-title_wr><p class=board-view-title>"+s.title()+"</p></div><ul class=board-view-ul><li><div class=board-view-inner><div class=k>첨부파일</div><div class=v><ul class=view-file-list>"+items+"</ul></div></div></li><li><div class=board-view-inner><div class=content>소상공인 지원</div></div></li></ul></div>";
    }
    @ParameterizedTest @ValueSource(booleans={true,false}) void budgetAndHeaderRulesRemainBounded(boolean gn){var s=ProvinceNextDownloadCases.selectCase(gn);var b=AnnouncementAttachmentBbsOfficialObservationTest.selectBudget(s.profile(),true,false);assertThat(b.maximumRequests).isEqualTo(6);assertThat(b.maximumBytes).isEqualTo(23*1024*1024);assertThat(s.profile().selectUtf8DispositionOctets()).isFalse();if(gn)assertThat(s.profile().selectLegacyBinaryContentTypes()).isEmpty();else assertThat(s.profile().selectLegacyBinaryContentTypes()).containsExactly("application/x-msdownload");}
    @ParameterizedTest @ValueSource(booleans={true,false}) void officialAttachmentsProduceDirectGetWithoutExecutingCompanions(boolean gn){var s=ProvinceNextDownloadCases.selectCase(gn);var r=s.profile().selectDescriptors(s.source(),selectPage(gn,selectItem(gn,1,"hwpx")+selectItem(gn,2,"pdf")));assertThat(r.status()).isEqualTo("FOUND");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(2).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(d.postForm()).isEmpty();assertThat(s.profile().selectApprovedRequest(d.fetchUri())).isTrue();assertThat(d.toString()).doesNotContain("지원","https");});}
    @ParameterizedTest @ValueSource(booleans={true,false}) void goodFilesSurviveUnknownLinksAndUnsupportedFormats(boolean gn){var s=ProvinceNextDownloadCases.selectCase(gn);var r=s.profile().selectDescriptors(s.source(),selectPage(gn,selectItem(gn,1,"hwpx")+selectItem(gn,2,"xlsx")+"<a href='/unknown'>미확인</a>"));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(2);assertThat(r.descriptors().getFirst().downloadAllowed()).isTrue();assertThat(r.descriptors().getLast().downloadAllowed()).isFalse();}
    @ParameterizedTest @ValueSource(booleans={true,false}) void detectsAbsentChangedDuplicateAndLimitedFiles(boolean gn){var s=ProvinceNextDownloadCases.selectCase(gn);var p=s.profile();assertThat(p.selectDescriptors(s.source(),selectPage(gn,"")).status()).isEqualTo("NO_FILES");for(String bad:List.of("<html>오류</html>",selectPage(gn,"")+selectPage(gn,""),selectPage(gn,"").replace("첨부파일","다른 영역")))assertThat(p.selectDescriptors(s.source(),bad).complete()).isFalse();var r=p.selectDescriptors(s.source(),selectPage(gn,IntStream.rangeClosed(1,11).mapToObj(i->selectItem(gn,i,"pdf")).collect(Collectors.joining())));assertThat(r.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(r.descriptors()).hasSize(10);String item=selectItem(gn,1,"hwpx");assertThat(p.selectDescriptors(s.source(),selectPage(gn,item+item)).descriptors()).hasSize(1);}
    @ParameterizedTest @ValueSource(booleans={true,false}) void titleSourceIdentityAndPolicyRemainRequired(boolean gn)throws Exception{var sample=ProvinceNextDownloadCases.selectCase(gn);var p=sample.profile();var s=sample.source();assertThat(p.selectDetailUri(s).toString()).isEqualTo(s.sourceUrl());assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source(s.providerCode(),s.providerNoticeId(),s.sourceUrl(),"LGS-000001",s.listParserProfileCode()))).isInstanceOf(IllegalArgumentException.class);var page=Jsoup.parse(selectPage(gn,selectItem(gn,1,"hwpx")));AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,sample.title(),sample.titleLayout());assertThatThrownBy(()->AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"다른 제목",sample.titleLayout())).isInstanceOf(AssertionError.class);var d=new AnnouncementSourceClassificationEngine().selectDecision(new AnnouncementSourceClassificationInput("LOCAL_GOV_NOTICE",sample.title(),null,null,List.of(),AnnouncementSourceClassificationCodes.BodySourceCode.NONE,AnnouncementSourceClassificationCodes.BodyAvailabilityCode.UNAVAILABLE),AnnouncementAttachmentRealFileQaTest.selectDraftRuleSet());assertThat(AnnouncementAttachmentBbsOfficialObservationTest.selectTitleMayProceed(d)).isTrue();}
    @ParameterizedTest @ValueSource(booleans={true,false}) void knownListSearchFieldsAreNotForwardedToDetail(boolean gn){var sample=ProvinceNextDownloadCases.selectCase(gn);var s=sample.source();var n=new AnnouncementSourceIdentityNormalizer();String url=s.sourceUrl()+(gn?"&conTitle=&conGosiGbn=&conIfmStdt=2026-01-01&conIfmEnddt=2026-09-30&pageLine=10&page=2&searchCnt=1":"&pageIndex=2&cl1CdValue=&sdate=2026-01-01&edate=2026-09-30");var source=new AttachmentDiscoveryProfile.Source(s.providerCode(),n.hash(n.canonicalizeUrl(url)),url,s.localSourceCode(),s.listParserProfileCode());assertThat(sample.profile().selectDetailUri(source).toString()).isEqualTo(s.sourceUrl());}
    @ParameterizedTest @ValueSource(booleans={true,false}) void restrictsMenuQueryHostPostAndRedirect(boolean gn){var sample=ProvinceNextDownloadCases.selectCase(gn);var p=sample.profile();var detail=p.selectDetailUri(sample.source());var file=p.selectDescriptors(sample.source(),selectPage(gn,selectItem(gn,1,"hwpx"))).descriptors().getFirst().fetchUri();for(String bad:List.of(detail+"&extra=x",detail+(gn?"&sno=2":"&nttId=2"),detail.toString().replace("https:","http:"),detail.toString().replace(gn?"DOM_000000135003009001":"500487",gn?"DOM_000000135003009000":"500488"),file+"&extra=x",file.toString().replace(gn?"www.gyeongnam.go.kr":"minwon.chungnam.go.kr","evil.go.kr"),file.toString().replace(gn?"contentsSid=3651":"index=1",gn?"contentsSid=3652":"index=-1")))assertThat(p.selectApprovedRequest(URI.create(bad))).isFalse();assertThat(p.selectApprovedRequest(new Request(file,"POST",Map.of("x","y")))).isFalse();assertThat(p.selectApprovedRequest(Request.selectGet(detail),Request.selectGet(file))).isFalse();}
    @ParameterizedTest @ValueSource(booleans={true,false}) void activeAndMalformedLinksKeepOtherGoodFiles(boolean gn){var s=ProvinceNextDownloadCases.selectCase(gn);String item=selectItem(gn,1,"hwpx");for(String bad:List.of(item.replace("href=","onmouseover='x()' href="),item.replace(gn?"contentsSid=3651":"mode=download",gn?"contentsSid=1":"mode=other"))){var r=s.profile().selectDescriptors(s.source(),selectPage(gn,bad+selectItem(gn,2,"hwpx")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}}
    @Test void mismatchedPreviewAndListenAreWarningsNotDownloadLoss(){var s=ProvinceNextDownloadCases.selectCase(false);String item=selectItem(false,1,"hwpx");for(String bad:List.of(item.replace("previewEncodingUrlAjax(","evil();previewEncodingUrlAjax("),item.replace("preListenEncodingUrlAjax(","evil();preListenEncodingUrlAjax("))){var r=s.profile().selectDescriptors(s.source(),selectPage(false,bad));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}}
    @Test void filenameTraversalIsNotAnApprovedGyeongnamDownload(){var p=ProvinceNextDownloadCases.selectCase(true).profile();for(String fn:List.of("../공고.hwpx","%2e%2e.hwpx","a/b.hwpx","bad\nhwpx"))assertThat(p.selectApprovedRequest(URI.create("https://www.gyeongnam.go.kr/index.gyeong?contentsSid=3651&fn="+URLEncoder.encode(fn,StandardCharsets.UTF_8)))).isFalse();}
    @Test void chungnamReusesObservedCitynetResponseWithoutBroadeningOtherMime()throws Exception{var p=(AttachmentDownloadFlowProfile)ProvinceNextDownloadCases.selectCase(false).profile();Path binary=temporary.resolve("fixture.hwp");Files.write(binary,new byte[]{(byte)0xd0,(byte)0xcf,0x11,(byte)0xe0,(byte)0xa1,(byte)0xb1,0x1a,(byte)0xe1});String header=new String("attachment; filename=\"지원.hwp\"".getBytes(java.nio.charset.Charset.forName("EUC-KR")),StandardCharsets.ISO_8859_1);var request=Request.selectGet(URI.create(selectFile(1)));var normalized=p.selectDownload(request,binary,100,(r,m)->new Download(8,"a".repeat(64),"application/file",header));assertThat(normalized.contentDisposition()).contains("지원.hwp");assertThat(new AttachmentFileTypeValidator().selectFormat(binary,normalized,"HWP",false,p.selectLegacyBinaryContentTypes())).isEqualTo("HWP");assertThatThrownBy(()->p.selectDownload(request,binary,100,(r,m)->new Download(8,"a".repeat(64),"application/x-msdownload",header))).isInstanceOf(java.io.IOException.class);}
}
