package com.saneb.domain.announcementattachment.qa;

import static org.assertj.core.api.Assertions.*;
import java.net.URI;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import com.saneb.domain.announcementattachment.discovery.AttachmentDiscoveryProfile;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.classification.*;

class SancheongDownloadContractTest {
    private final AnnouncementAttachmentBbsOfficialObservationTest.ObservationCase sample=SancheongDownloadCases.selectCase();
    private String selectItem(int id,String ext){String name="공고 "+id+"."+ext;return "<li><a href='/downloadBbsFile.do?atchmnflNo="+id+"'><img src='/common/images/board/file/ico_"+ext+".gif' alt='"+name+"'><span>"+name+"</span></a><a href='/previewBbs.do?atchmnflNo="+id+"' class=cnt_btn_view><span class=skip>"+name+"</span>미리보기</a></li>";}
    private String selectPage(String items){return "<table class=bbs_default_view><tr><th>제목</th><td class=subject>"+sample.title()+"</td></tr><tr><th>내용</th><td class=subject>소상공인 지원</td></tr><tr><th>파일</th><td><ul class=brd_file>"+items+"</ul></td></tr></table>";}
    @Test void boundedBudgetAndObservedMimeAreRegionSpecific(){var b=AnnouncementAttachmentBbsOfficialObservationTest.selectBudget(sample.profile(),true,false);assertThat(b.maximumRequests).isEqualTo(6);assertThat(b.maximumBytes).isEqualTo(23*1024*1024);assertThat(sample.profile().selectLegacyBinaryContentTypes()).containsExactly("application/octer-stream");assertThat(sample.profile().selectUtf8DispositionOctets()).isTrue();}
    @Test void collectsDirectFilesWithoutFetchingPairedPreviews(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwpx")+selectItem(2,"hwpx")));assertThat(r.status()).isEqualTo("FOUND");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(2).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(d.postForm()).isEmpty();assertThat(sample.profile().selectApprovedRequest(d.fetchUri())).isTrue();assertThat(d.toString()).doesNotContain("공고","https");});}
    @Test void goodFilesSurviveUnknownLinksAndUnsupportedFormats(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwpx")+selectItem(2,"xlsx")+"<li><a href='/unknown'>알 수 없음</a></li>"));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(2);assertThat(r.descriptors().getFirst().downloadAllowed()).isTrue();assertThat(r.descriptors().getLast().downloadAllowed()).isFalse();}
    @Test void distinguishesAbsentChangedDuplicateAndLimitedFiles(){var p=sample.profile();assertThat(p.selectDescriptors(sample.source(),selectPage("")).status()).isEqualTo("NO_FILES");for(String bad:List.of("<html>오류</html>",selectPage("<li></li>"),selectPage("")+selectPage(""),selectPage("").replace("<th>파일</th>","<th>다른 셀</th>")))assertThat(p.selectDescriptors(sample.source(),bad).complete()).isFalse();var r=p.selectDescriptors(sample.source(),selectPage(IntStream.rangeClosed(1,11).mapToObj(i->selectItem(i,"pdf")).collect(Collectors.joining())));assertThat(r.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(r.descriptors()).hasSize(10);String item=selectItem(1,"hwpx");assertThat(p.selectDescriptors(sample.source(),selectPage(item+item)).descriptors()).hasSize(1);}
    @Test void mismatchedPreviewDoesNotDiscardSuccessfulDescriptor(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwpx").replace("/previewBbs.do?atchmnflNo=1","/previewBbs.do?atchmnflNo=2")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}
    @Test void titleSourceIdentityAndTitlePolicyAreRequired()throws Exception{var p=sample.profile();var s=sample.source();assertThat(p.selectDetailUri(s).toString()).isEqualTo(s.sourceUrl());assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source(s.providerCode(),s.providerNoticeId(),s.sourceUrl(),"LGS-000001",s.listParserProfileCode()))).isInstanceOf(IllegalArgumentException.class);var page=Jsoup.parse(selectPage(selectItem(1,"hwpx")));AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,sample.title(),sample.titleLayout());assertThatThrownBy(()->AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"다른 제목",sample.titleLayout())).isInstanceOf(AssertionError.class);var d=new AnnouncementSourceClassificationEngine().selectDecision(new AnnouncementSourceClassificationInput("LOCAL_GOV_NOTICE",sample.title(),null,null,List.of(),AnnouncementSourceClassificationCodes.BodySourceCode.NONE,AnnouncementSourceClassificationCodes.BodyAvailabilityCode.UNAVAILABLE),AnnouncementAttachmentRealFileQaTest.selectDraftRuleSet());assertThat(AnnouncementAttachmentBbsOfficialObservationTest.selectTitleMayProceed(d)).isTrue();}
    @Test void restrictsBoardQueryPostAndRedirect(){var p=sample.profile();var detail=p.selectDetailUri(sample.source());var file=p.selectDescriptors(sample.source(),selectPage(selectItem(1,"hwpx"))).descriptors().getFirst().fetchUri();for(String bad:List.of(detail+"&nttNo=2",detail+"&extra=x",detail.toString().replace("bbsNo=118","bbsNo=1"),detail.toString().replace("https:","http:"),file+"&extra=x",file.toString().replace("www.sancheong.go.kr","evil.go.kr"),file.toString().replace("/downloadBbsFile.do","/previewBbs.do")))assertThat(p.selectApprovedRequest(URI.create(bad))).isFalse();assertThat(p.selectApprovedRequest(new Request(file,"POST",Map.of("x","y")))).isFalse();assertThat(p.selectApprovedRequest(Request.selectGet(detail),Request.selectGet(file))).isFalse();}
    @Test void detectsMalformedIconsAndActiveContentWithoutLosingOtherFiles(){var p=sample.profile();String item=selectItem(1,"hwpx");for(String bad:List.of(item.replace("alt='공고 1.hwpx'","alt='다른 파일'"),item.replace("<span>공고","<span><script>x</script>공고"),item.replace("href='/download","onclick='x()' href='/download"))){var r=p.selectDescriptors(sample.source(),selectPage(bad+selectItem(2,"hwpx")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}assertThat(p.selectDescriptors(sample.source(),selectPage(item)+"<a href='/other.pdf'>외부</a>").complete()).isTrue();}
}
