package com.saneb.domain.announcementattachment.qa;

import static org.assertj.core.api.Assertions.*;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.*;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Test;
import com.saneb.domain.announcementattachment.discovery.AttachmentDiscoveryProfile;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.classification.*;

class UiryeongDownloadContractTest {
    private final AnnouncementAttachmentBbsOfficialObservationTest.ObservationCase sample=UiryeongDownloadCases.selectCase();
    private String selectEncoded(String value){return URLEncoder.encode(value,StandardCharsets.UTF_8);}
    private String selectItem(int id,String ext){
        String name="지원 공고 "+id+"."+ext,stored="stored_"+id+"."+ext,path="/ntishome/file/upload/ofr/ofr/20260319";
        String query="file_path="+path+"&sys_file_nm="+selectEncoded(stored)+"&user_file_nm="+selectEncoded(name);
        String preview=selectEncoded(selectEncoded(path+":"+stored+":"+name));
        return "<li class=gosiWrap><img src='/images/new/Potal/board/fileIcon.png' alt='다운로드'>&nbsp;<a href='https://eminwon.uiryeong.go.kr/emwp/jsp/ofr/FileDown.jsp?\t"+query+"'>"+name+"\t</a><a href='/customuser/synap.uiryeong?p="+preview+"' target=_blank><img src='/images/new/Potal/board/viwerIcon.png' alt='바로보기'></a></li>";
    }
    private String selectPage(String items){return "<div class=boardViewWrap><div class=bdvTitWrap><p class=bdvTit>"+sample.title()+"</p></div><div class=bdvInfo><dl class='bdvInfo-full fileBox'><dt>첨부</dt><dd><ul class=fileBoxs>"+items+"</ul></dd></dl></div><div class=bdvCntWrap>소상공인 지원</div></div>";}
    @Test void budgetIsBoundedWithoutMimeOrDispositionException(){var b=AnnouncementAttachmentBbsOfficialObservationTest.selectBudget(sample.profile(),true,false);assertThat(b.maximumRequests).isEqualTo(6);assertThat(b.maximumBytes).isEqualTo(23*1024*1024);assertThat(sample.profile().selectLegacyBinaryContentTypes()).isEmpty();assertThat(sample.profile().selectUtf8DispositionOctets()).isFalse();}
    @Test void directFilesAreCollectedWithoutFetchingPairedPreviews(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp")+selectItem(2,"hwpx")));assertThat(r.status()).isEqualTo("FOUND");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(2).allSatisfy(d->{assertThat(d.downloadAllowed()).isTrue();assertThat(d.documentRole()).isEqualTo("UNKNOWN");assertThat(d.postForm()).isEmpty();assertThat(sample.profile().selectApprovedRequest(d.fetchUri())).isTrue();assertThat(d.fetchUri().getRawQuery()).doesNotContain("\t");assertThat(d.toString()).doesNotContain("공고","https");});}
    @Test void goodFilesSurviveUnsupportedFormatsAndUnknownLinks(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp")+selectItem(2,"xlsx")+"<li><a href='/unknown'>미확인</a></li>"));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(2);assertThat(r.descriptors().getFirst().downloadAllowed()).isTrue();assertThat(r.descriptors().getLast().downloadAllowed()).isFalse();}
    @Test void distinguishesAbsentChangedDuplicateAndLimitedFiles(){var p=sample.profile();assertThat(p.selectDescriptors(sample.source(),selectPage("")).status()).isEqualTo("NO_FILES");for(String bad:List.of("<html>오류</html>",selectPage("<li></li>"),selectPage("")+selectPage(""),selectPage("").replace("<dt>첨부</dt>","<dt>다른 영역</dt>")))assertThat(p.selectDescriptors(sample.source(),bad).complete()).isFalse();var r=p.selectDescriptors(sample.source(),selectPage(IntStream.rangeClosed(1,11).mapToObj(i->selectItem(i,"pdf")).collect(Collectors.joining())));assertThat(r.status()).isEqualTo("LIMIT_EXCEEDED");assertThat(r.descriptors()).hasSize(10);String item=selectItem(1,"hwp");assertThat(p.selectDescriptors(sample.source(),selectPage(item+item)).descriptors()).hasSize(1);}
    @Test void mismatchedPreviewKeepsGoodDownloadAndRecordsUnresolved(){String item=selectItem(1,"hwp");var r=sample.profile().selectDescriptors(sample.source(),selectPage(item.replace("synap.uiryeong?p=","synap.uiryeong?p=wrong")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}
    @Test void titleSourceIdentityAndTitlePolicyAreRequired()throws Exception{var p=sample.profile();var s=sample.source();assertThat(p.selectDetailUri(s).toString()).isEqualTo(s.sourceUrl());assertThatThrownBy(()->p.selectDetailUri(new AttachmentDiscoveryProfile.Source(s.providerCode(),s.providerNoticeId(),s.sourceUrl(),"LGS-000001",s.listParserProfileCode()))).isInstanceOf(IllegalArgumentException.class);var page=Jsoup.parse(selectPage(selectItem(1,"hwp")));AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,sample.title(),sample.titleLayout());assertThatThrownBy(()->AnnouncementAttachmentBbsOfficialObservationTest.validateTitle(page,"다른 제목",sample.titleLayout())).isInstanceOf(AssertionError.class);var d=new AnnouncementSourceClassificationEngine().selectDecision(new AnnouncementSourceClassificationInput("LOCAL_GOV_NOTICE",sample.title(),null,null,List.of(),AnnouncementSourceClassificationCodes.BodySourceCode.NONE,AnnouncementSourceClassificationCodes.BodyAvailabilityCode.UNAVAILABLE),AnnouncementAttachmentRealFileQaTest.selectDraftRuleSet());assertThat(AnnouncementAttachmentBbsOfficialObservationTest.selectTitleMayProceed(d)).isTrue();}
    @Test void gosiNoDistinguishesNoticesSharingTheSameDataSid(){var s=sample.source();String other=s.sourceUrl().replace("gosiNo=35341","gosiNo=34918");var n=new AnnouncementSourceIdentityNormalizer();String id=n.hash(n.canonicalizeUrl(other));assertThat(id).isNotEqualTo(s.providerNoticeId());var otherSource=new AttachmentDiscoveryProfile.Source(s.providerCode(),id,other,s.localSourceCode(),s.listParserProfileCode());assertThat(sample.profile().selectDetailUri(otherSource).toString()).contains("dataSid=316445","gosiNo=34918");var first=sample.profile().selectDescriptors(s,selectPage(selectItem(1,"hwp"))).descriptors().getFirst();var second=sample.profile().selectDescriptors(otherSource,selectPage(selectItem(1,"hwp"))).descriptors().getFirst();assertThat(first.locator()).isNotEqualTo(second.locator());}
    @Test void restrictsBoardQueryPostAndRedirect(){var p=sample.profile();var detail=p.selectDetailUri(sample.source());var file=p.selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp"))).descriptors().getFirst().fetchUri();for(String bad:List.of(detail+"&gosiNo=2",detail+"&extra=x",detail.toString().replace("BBS_0000070","BBS_0000001"),detail.toString().replace("https:","http:"),detail.toString().replace("&gosiNo=35341",""),file+"&extra=x",file.toString().replace("eminwon.uiryeong.go.kr","evil.go.kr"),file.toString().replace("/20260319","/../private")))assertThat(p.selectApprovedRequest(URI.create(bad))).isFalse();assertThat(p.selectApprovedRequest(new Request(file,"POST",Map.of("x","y")))).isFalse();assertThat(p.selectApprovedRequest(Request.selectGet(detail),Request.selectGet(file))).isFalse();}
    @Test void normalizesOnlyTheObservedLeadingTabAndPreservesOtherFiles(){String item=selectItem(1,"hwp");for(String bad:List.of(item.replace("?\tfile_path=","?\t\tfile_path="),item.replace("sys_file_nm=","sys_file_nm=%09"),item.replace("href='https://eminwon","onclick='x()' href='https://eminwon"),item.replace(">지원 공고 1.hwp\t</a>",">다른 이름</a>"))){var r=sample.profile().selectDescriptors(sample.source(),selectPage(bad+selectItem(2,"hwp")));assertThat(r.complete()).isFalse();assertThat(r.descriptors()).hasSize(1);}}
    @Test void onlyOfficialAttachmentCellIsUsed(){var r=sample.profile().selectDescriptors(sample.source(),selectPage(selectItem(1,"hwp"))+"<a href='/unrelated.pdf'>메뉴 파일</a>");assertThat(r.complete()).isTrue();assertThat(r.descriptors()).hasSize(1);}
}
