package com.saneb.domain.announcementattachment.discovery;
import com.saneb.domain.announcementattachment.vo.AttachmentSetEvidence;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.CapitalThirdNoticePage;
import com.saneb.domain.announcementsource.provider.content.DaejeonNextNoticePage;
import com.saneb.domain.announcementsource.provider.content.DaejeonNextNoticePage.Site;
import java.net.URI;
import java.util.*;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;
/** 빈 action은 실행하지 않는다. 실측된 공식 파일 서버로 세 문자열만 직접 전달한다. */
final class DaejeonNextAttachmentDiscoveryProfile implements AttachmentDiscoveryProfile,AttachmentDetailLimitProfile {
    private static final String DOWNLOAD="/emwp/jsp/ofr/FileDown.jsp";
    private static final Set<String> FIELDS=Set.of("user_file_nm","sys_file_nm","file_path");
    private final Site site;private final String code,hash;private final AnnouncementSourceIdentityNormalizer normalizer=new AnnouncementSourceIdentityNormalizer();
    DaejeonNextAttachmentDiscoveryProfile(Site s){site=s;code="LOCAL_"+s+"_BOARD_V1";hash=AttachmentProfileFingerprint.selectHash("DAEJEON_NEXT:1|"+s+"|"+s.sourceCode+"|"+s.parser+"|detailBytes="+selectDetailMaximumBytes()+"|https443|fixed-post|literal3|same-request|unknown-role|limit10|"+AttachmentProfileFingerprint.selectHash("PAGE:1",DaejeonNextNoticePage.class)+"|"+AttachmentProfileFingerprint.selectHash("QUERY:1",CapitalThirdNoticePage.class)+"|"+AttachmentProfileFingerprint.selectHash("CALL:1",AttachmentDownloadInvocation.class),getClass());}
    @Override public long selectDetailMaximumBytes(){return (site==Site.YUSEONG?2L:1L)*1024*1024;}
    @Override public String selectProviderCode(){return "LOCAL_GOV_NOTICE";}
    @Override public String selectProfileCode(){return code;}
    @Override public String selectProfileHash(){return hash;}
    @Override public Set<String> selectApprovedHosts(){return Set.of(site.host,site.fileHost);}
    @Override public List<SourceBinding> selectSourceBindings(){return List.of(new SourceBinding(site.sourceCode,site.parser));}
    @Override public URI selectDetailUri(String id){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public Result selectDescriptors(String id,String html){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public URI selectDetailUri(Source s){try{if(s==null||!selectProviderCode().equals(s.providerCode())||!site.sourceCode.equals(s.localSourceCode())||!site.parser.equals(s.listParserProfileCode())||s.sourceUrl()==null||s.sourceUrl().length()>4096||!normalizer.hash(normalizer.canonicalizeUrl(s.sourceUrl())).equals(s.providerNoticeId()))throw new IllegalArgumentException();return DaejeonNextNoticePage.selectDetailUri(site,URI.create(s.sourceUrl()));}catch(IllegalArgumentException e){throw new IllegalArgumentException("PROFILE_REQUIRED");}}
    private boolean selectSafeUri(URI u){return u!=null&&u.toASCIIString().length()<=8192&&"https".equals(u.getScheme())&&(u.getPort()==-1||u.getPort()==443)&&u.getUserInfo()==null&&u.getFragment()==null&&u.getRawPath()!=null&&u.getRawPath().equals(u.getPath())&&u.equals(u.normalize());}
    @Override public boolean selectApprovedRequest(URI u){try{return selectSafeUri(u)&&site.host.equals(u.getHost())&&u.equals(DaejeonNextNoticePage.selectDetailUri(site,u));}catch(IllegalArgumentException e){return false;}}
    private boolean selectName(String v){return v!=null&&!v.isBlank()&&v.length()<=500&&!v.contains("/")&&!v.contains("\\")&&!v.contains("..")&&!v.contains("%")&&v.indexOf('\ufffd')<0&&v.codePoints().noneMatch(Character::isISOControl);}
    @Override public boolean selectApprovedRequest(Request r){if(r==null)return false;if("GET".equals(r.method()))return r.form().isEmpty()&&selectApprovedRequest(r.uri());if(!"POST".equals(r.method())||!selectSafeUri(r.uri())||!site.fileHost.equals(r.uri().getHost())||!DOWNLOAD.equals(r.uri().getPath())||r.uri().getRawQuery()!=null)return false;var f=r.form();return f.keySet().equals(FIELDS)&&selectName(f.get("user_file_nm"))&&selectName(f.get("sys_file_nm"))&&f.get("file_path").matches("/ntishome/file/upload/ofr/ofr/[0-9]{8}");}
    @Override public boolean selectApprovedRequest(Request first,Request next){return first!=null&&first.equals(next)&&selectApprovedRequest(next);}
    private boolean selectForm(Element f,List<String> args){if(f==null||!"form".equals(f.tagName())||!"fileForm".equals(f.id())||!"fileForm".equals(f.attr("name"))||!"post".equals(f.attr("method"))||!f.attr("action").isEmpty()||f.childrenSize()!=3||f.select(":root > input[type=hidden]").size()!=3||!f.children().stream().map(e->e.attr("name")).collect(java.util.stream.Collectors.toSet()).equals(FIELDS))return false;if(args==null)return f.children().stream().allMatch(e->e.val().isEmpty());return f.select("input[name=user_file_nm]").val().equals(args.get(1))&&f.select("input[name=sys_file_nm]").val().equals(args.get(0))&&f.select("input[name=file_path]").val().equals(args.get(2));}
    @Override public Result selectDescriptors(Source s,String html){URI detail=selectDetailUri(s);if(html==null||html.length()>selectDetailMaximumBytes())return selectFailed("ATTACHMENT_DETAIL_UNAVAILABLE");var page=Jsoup.parse(html,detail.toASCIIString());Element area;try{area=DaejeonNextNoticePage.selectAttachments(site,page).clone();}catch(IllegalArgumentException e){return selectFailed("ATTACHMENT_SELECTOR_CHANGED");}if(site==Site.YUSEONG){var forms=page.select("form#fileForm");if(forms.size()!=1||!selectForm(forms.getFirst(),null))return selectFailed("ATTACHMENT_DOWNLOAD_FORM_CHANGED");}
        var files=new LinkedHashMap<String,Descriptor>();boolean unresolved=false,exceeded=false;String notice=CapitalThirdNoticePage.selectParameters(detail.getRawQuery()).get(site.idKey);
        for(var a:area.select(":root > a[onclick]"))try{var args=AttachmentDownloadInvocation.selectArguments(a.attr("onclick"),"fn_egov_downFile",true,true);if(args.size()!=3||!(site==Site.YUSEONG?"#":"#file").equals(a.attr("href"))||!args.get(0).equals(a.text().strip()))continue;var form=site==Site.DAEDEOK?a.previousElementSibling():null;if(site==Site.DAEDEOK&&!selectForm(form,args))continue;var request=new Request(URI.create("https://"+site.fileHost+DOWNLOAD),"POST",Map.of("user_file_nm",args.get(0),"sys_file_nm",args.get(1),"file_path",args.get(2)));if(!selectApprovedRequest(request))continue;String id=normalizer.hash(args.get(2)+"\n"+args.get(1)),format=selectFormat(args.get(0));boolean supported=format!=null&&format.equals(selectFormat(args.get(1)));var d=new Descriptor(request.uri(),new AttachmentSetEvidence.Locator(code,DOWNLOAD,Map.of("noticeId",notice,"attachmentId",id)),args.get(0),supported?format:null,"UNKNOWN",supported,request.form());var old=files.get(id);if(old!=null){if(!old.equals(d))unresolved=true;}else if(files.size()==10){exceeded=true;continue;}else files.put(id,d);
            var residue=a.clone();for(var icon:residue.select(":root > i.ir.ir-bbs.ir-file.left"))if(icon.text().isBlank()&&icon.children().isEmpty()&&icon.attributes().size()==1)icon.remove();if(!residue.children().isEmpty())unresolved=true;a.remove();if(form!=null)form.remove();
            if(site==Site.YUSEONG)for(var preview:area.select(":root > a[onclick]")){String raw=preview.attr("onclick"),prefix="fn_egov_previewFile(";if("#".equals(preview.attr("href"))&&"미리보기".equals(preview.text().strip())&&raw.startsWith(prefix)&&args.equals(AttachmentDownloadInvocation.selectArguments("fn_egov_downFile("+raw.substring(prefix.length()),"fn_egov_downFile",true,true)))preview.remove();}
        }catch(IllegalArgumentException e){unresolved=true;}
        if(!area.text().isBlank()||!area.select("a,button,input,form,iframe,object,embed,script,img,[onclick],[href]").isEmpty())unresolved=true;if(exceeded)return new Result("LIMIT_EXCEEDED",false,List.copyOf(files.values()),List.of("ATTACHMENT_FILE_LIMIT"));if(unresolved)return new Result("FAILED",false,List.copyOf(files.values()),List.of("ATTACHMENT_LINK_UNRESOLVED"));return new Result(files.isEmpty()?"NO_FILES":"FOUND",true,List.copyOf(files.values()),List.of());}
    private String selectFormat(String n){String e=n.contains(".")?n.substring(n.lastIndexOf('.')+1).toUpperCase(Locale.ROOT):"";return Set.of("PDF","HWP","HWPX").contains(e)?e:null;}
    private Result selectFailed(String code){return new Result("FAILED",false,List.of(),List.of(code));}
}
