package com.saneb.domain.announcementattachment.discovery;

import com.saneb.domain.announcementattachment.vo.AttachmentSetEvidence;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.CapitalThirdNoticePage;
import com.saneb.domain.announcementsource.provider.content.IncheonSecondNoticePage;
import com.saneb.domain.announcementsource.provider.content.IncheonSecondNoticePage.Site;
import java.net.URI;
import java.util.*;
import java.util.regex.Pattern;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;

/** 미리보기·압축 다운로드·JavaScript는 실행하지 않는다. 공식 미추홀 파일 폼 목적지는 고정한다. */
final class IncheonSecondAttachmentDiscoveryProfile implements AttachmentDiscoveryProfile {
    private static final String DIRECT="/main/bbs/bbsMsgFileDown.do",PROXY="/other/crawling_file_down.do",REMOTE="https://eminwon.michuhol.go.kr/emwp/jsp/ofr/FileDownNew.jsp";
    private static final Set<String> FIELDS=Set.of("downloadUrl","userFileNm","sysFileNm","filePath","fileOrigin");
    private static final Pattern OPAQUE=Pattern.compile("[A-Za-z0-9+/]{22,}={0,2}$");
    private final Site site;private final String code,hash;
    private final AnnouncementSourceIdentityNormalizer normalizer=new AnnouncementSourceIdentityNormalizer();
    IncheonSecondAttachmentDiscoveryProfile(Site s){site=s;code="LOCAL_"+s+"_BOARD_V1";hash=AttachmentProfileFingerprint.selectHash("INCHEON_SECOND:1|"+s+"|"+s.sourceCode+"|SPRING_BBS|https443|fixed-proxy-destination|same-request-only|limit10|unknown-role|"+AttachmentProfileFingerprint.selectHash("PAGE:1",IncheonSecondNoticePage.class)+"|"+AttachmentProfileFingerprint.selectHash("QUERY:1",CapitalThirdNoticePage.class),getClass());}
    @Override public String selectProviderCode(){return "LOCAL_GOV_NOTICE";}
    @Override public String selectProfileCode(){return code;}
    @Override public String selectProfileHash(){return hash;}
    @Override public List<SourceBinding> selectSourceBindings(){return List.of(new SourceBinding(site.sourceCode,"SPRING_BBS"));}
    @Override public Set<String> selectApprovedHosts(){return Set.of(site.host);}
    @Override public URI selectDetailUri(String id){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public Result selectDescriptors(String id,String html){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public URI selectDetailUri(Source s){try{if(s==null||!selectProviderCode().equals(s.providerCode())||!site.sourceCode.equals(s.localSourceCode())||!"SPRING_BBS".equals(s.listParserProfileCode())||s.sourceUrl()==null||s.sourceUrl().length()>4096||!normalizer.hash(normalizer.canonicalizeUrl(s.sourceUrl())).equals(s.providerNoticeId()))throw new IllegalArgumentException();return IncheonSecondNoticePage.selectDetailUri(site,URI.create(s.sourceUrl()));}catch(IllegalArgumentException e){throw new IllegalArgumentException("PROFILE_REQUIRED");}}
    private boolean selectSafeUri(URI u){return u!=null&&u.toASCIIString().length()<=8192&&"https".equals(u.getScheme())&&site.host.equals(u.getHost())&&(u.getPort()==-1||u.getPort()==443)&&u.getUserInfo()==null&&u.getFragment()==null&&u.equals(u.normalize())&&u.getRawPath()!=null&&u.getRawPath().equals(u.getPath());}
    @Override public boolean selectApprovedRequest(URI u){try{if(!selectSafeUri(u))return false;if(site.path.equals(u.getPath()))return u.equals(IncheonSecondNoticePage.selectDetailUri(site,u));if(site!=Site.JEMULPO||!DIRECT.equals(u.getPath()))return false;var q=CapitalThirdNoticePage.selectParameters(u.getRawQuery());return q.keySet().equals(Set.of("bcd","msg_seq","fileno"))&&"announce".equals(q.get("bcd"))&&selectNumber(q.get("msg_seq"))&&selectNumber(q.get("fileno"));}catch(IllegalArgumentException e){return false;}}
    @Override public boolean selectApprovedRequest(Request r){if(r==null)return false;if("GET".equals(r.method()))return r.form().isEmpty()&&selectApprovedRequest(r.uri());if(site!=Site.MICHUHOL||!"POST".equals(r.method())||!selectSafeUri(r.uri())||!PROXY.equals(r.uri().getPath())||r.uri().getRawQuery()!=null)return false;var f=r.form();return f.keySet().equals(FIELDS)&&REMOTE.equals(f.get("downloadUrl"))&&selectOpaque(f.get("userFileNm"))&&selectOpaque(f.get("sysFileNm"))&&f.get("filePath").length()<=2048&&f.get("filePath").matches("/ntisho[A-Za-z0-9+/]{43,}={0,2}")&&selectName(f.get("fileOrigin"));}
    @Override public boolean selectApprovedRequest(Request initial,Request next){return initial!=null&&initial.equals(next)&&selectApprovedRequest(next);}
    private boolean selectNumber(String s){return s!=null&&s.matches("[1-9][0-9]{0,14}");}
    private boolean selectOpaque(String s){return s!=null&&s.length()>=22&&s.length()<=2048&&OPAQUE.matcher(s).find()&&!s.contains("..")&&s.codePoints().noneMatch(Character::isISOControl)&&s.chars().noneMatch(c->"\\%<>:?#".indexOf(c)>=0);}
    private boolean selectName(String s){return s!=null&&!s.isBlank()&&s.length()<=500&&!s.contains("/")&&!s.contains("\\")&&!s.contains("..")&&s.indexOf('\ufffd')<0&&s.codePoints().noneMatch(Character::isISOControl);}
    /** 다섯 문자열만 선형으로 읽는다. 함수 호출이나 동적 표현식은 실행하지 않는다. */
    private List<String> selectArguments(String raw){if(raw==null||raw.length()>8192||!raw.startsWith("javascript:fnFileDown("))return List.of();int i="javascript:fnFileDown(".length();var out=new ArrayList<String>();for(int n=0;n<5;n++){while(i<raw.length()&&Character.isWhitespace(raw.charAt(i)))i++;if(i>=raw.length()||raw.charAt(i++)!='\'')return List.of();var v=new StringBuilder();boolean closed=false;while(i<raw.length()){char c=raw.charAt(i++);if(c=='\''){closed=true;break;}if(c=='\\'){if(i>=raw.length())return List.of();c=raw.charAt(i++);if(c!='\\'&&c!='\'')return List.of();}if(Character.isISOControl(c)||v.length()==2048)return List.of();v.append(c);}if(!closed)return List.of();out.add(v.toString());while(i<raw.length()&&Character.isWhitespace(raw.charAt(i)))i++;if(i>=raw.length()||raw.charAt(i++)!=(n==4?')':','))return List.of();}String tail=raw.substring(i).strip();return tail.isEmpty()||tail.equals(";")?List.copyOf(out):List.of();}
    private boolean selectAuxiliary(Element e,URI file,URI detail){try{String call=e.attr("onclick").replaceAll("\\s+","");String path;boolean preview;if(call.startsWith("location.href='")&&call.endsWith("'")){path=call.substring(15,call.length()-1);preview=false;}else if(call.startsWith("window.open('")&&call.endsWith("','_blank')")){path=call.substring(13,call.length()-11);preview=true;}else return false;URI u=detail.resolve(path);return selectSafeUri(u)&&(preview?"/main/bbs/bbsMsgFileView.do":DIRECT).equals(u.getPath())&&CapitalThirdNoticePage.selectParameters(u.getRawQuery()).equals(CapitalThirdNoticePage.selectParameters(file.getRawQuery()));}catch(IllegalArgumentException e1){return false;}}
    private boolean selectForm(org.jsoup.nodes.Document p){var forms=p.select("form#formCrawling[name=formCrawling]");if(forms.size()!=1)return false;var f=forms.getFirst();return "post".equalsIgnoreCase(f.attr("method"))&&PROXY.equals(f.attr("action"))&&f.childrenSize()==5&&f.select(":root > input[type=hidden]").size()==5&&f.children().stream().allMatch(e->e.val().isEmpty())&&f.children().stream().map(e->e.attr("name")).collect(java.util.stream.Collectors.toSet()).equals(FIELDS);}
    @Override public Result selectDescriptors(Source s,String html){URI detail=selectDetailUri(s);if(html==null||html.length()>1048576)return selectFailed("ATTACHMENT_DETAIL_UNAVAILABLE");var page=Jsoup.parse(html,detail.toASCIIString());Element area;try{area=IncheonSecondNoticePage.selectAttachments(site,page).clone();}catch(IllegalArgumentException e){return selectFailed("ATTACHMENT_SELECTOR_CHANGED");}if(site==Site.MICHUHOL&&!selectForm(page))return selectFailed("ATTACHMENT_DOWNLOAD_FORM_CHANGED");var files=new LinkedHashMap<String,Descriptor>();boolean unresolved=false,exceeded=false;String notice=CapitalThirdNoticePage.selectParameters(detail.getRawQuery()).get(site.idKey);
        String itemSelector=site==Site.JEMULPO?":root > ul > li":":root > a";for(var item:area.select(itemSelector))try{Element a=site==Site.JEMULPO?item.selectFirst(":root > p.tit > a"):item;if(a==null||a.hasAttr("onclick")||!a.children().isEmpty())continue;String name=a.text().strip();if(!selectName(name))continue;Request request;String id;
            if(site==Site.JEMULPO){URI u=detail.resolve(a.attr("href"));if(!DIRECT.equals(u.getPath())||!selectApprovedRequest(u))continue;var q=CapitalThirdNoticePage.selectParameters(u.getRawQuery());if(!notice.equals(q.get("msg_seq")))continue;request=Request.selectGet(u);id=normalizer.hash(notice+"\n"+q.get("fileno"));}
            else {var args=selectArguments(a.attr("href"));if(args.size()!=5||!name.equals(args.get(4)))continue;var f=Map.of("downloadUrl",args.get(0),"userFileNm",args.get(1),"sysFileNm",args.get(2),"filePath",args.get(3),"fileOrigin",args.get(4));request=new Request(URI.create("https://"+site.host+PROXY),"POST",f);if(!selectApprovedRequest(request))continue;id=normalizer.hash(args.get(3)+"\n"+args.get(2));}
            String ext=name.contains(".")?name.substring(name.lastIndexOf('.')+1).toUpperCase(Locale.ROOT):"";boolean supported=Set.of("PDF","HWP","HWPX").contains(ext);var d=new Descriptor(request.uri(),new AttachmentSetEvidence.Locator(code,site==Site.JEMULPO?DIRECT:PROXY,Map.of("noticeId",notice,"attachmentId",id)),name,supported?ext:null,"UNKNOWN",supported,request.form());var old=files.get(id);if(old!=null){if(!old.equals(d))unresolved=true;}else if(files.size()==10){exceeded=true;continue;}else files.put(id,d);
            if(site==Site.JEMULPO){var residual=item.clone();residual.select(":root > p.tit > a").remove();for(var span:residual.select(":root > p.tit > span.margin_l10"))if(span.children().isEmpty()&&span.text().matches("\\[[0-9.,]+(?:KByte|MByte|Byte)\\]"))span.remove();for(var button:residual.select(":root > div.btn-wrap > button"))if(selectAuxiliary(button,request.uri(),detail))button.remove();if(selectResidual(residual))unresolved=true;}item.remove();
        }catch(IllegalArgumentException e){unresolved=true;}
        if(site==Site.JEMULPO)for(var bulk:area.select(":root > a.alldown"))try{URI u=detail.resolve(bulk.attr("href"));if(!bulk.hasAttr("onclick")&&selectSafeUri(u)&&"/main/bbs/bbsMsgFileDownCompress.do".equals(u.getPath())&&CapitalThirdNoticePage.selectParameters(u.getRawQuery()).equals(Map.of("bcd","announce","msg_seq",notice)))bulk.remove();}catch(IllegalArgumentException ignored){ }
        if(selectResidual(area))unresolved=true;if(exceeded)return new Result("LIMIT_EXCEEDED",false,List.copyOf(files.values()),List.of("ATTACHMENT_FILE_LIMIT"));if(unresolved)return new Result("FAILED",false,List.copyOf(files.values()),List.of("ATTACHMENT_LINK_UNRESOLVED"));return new Result(files.isEmpty()?"NO_FILES":"FOUND",true,List.copyOf(files.values()),List.of());}
    private boolean selectResidual(Element e){return !e.text().isBlank()||!e.select("a,button,input,select,form,iframe,object,embed,script,[onclick],[href],img").isEmpty();}
    private Result selectFailed(String code){return new Result("FAILED",false,List.of(),List.of(code));}
}
