package com.saneb.domain.announcementattachment.discovery;

import com.saneb.domain.announcementattachment.vo.AttachmentSetEvidence;
import com.saneb.domain.announcementsource.localgov.support.AnnouncementSourceIdentityNormalizer;
import com.saneb.domain.announcementsource.provider.content.AttachmentPinnedDownloadClient.Request;
import com.saneb.domain.announcementsource.provider.content.CapitalThirdNoticePage;
import com.saneb.domain.announcementsource.provider.content.SeoulSeventhNoticePage;
import com.saneb.domain.announcementsource.provider.content.SeoulSeventhNoticePage.Site;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;

/** 기관별 공식 파일 링크만 수집한다. 미리보기·변환·음성·외부 iframe은 호출하지 않는다. */
final class SeoulSeventhAttachmentDiscoveryProfile implements AttachmentDiscoveryProfile {
    private final Site site;private final String code,hash;
    private final AnnouncementSourceIdentityNormalizer normalizer=new AnnouncementSourceIdentityNormalizer();
    SeoulSeventhAttachmentDiscoveryProfile(Site s){site=s;code="LOCAL_"+s+"_BOARD_V1";hash=AttachmentProfileFingerprint.selectHash("SEOUL_SEVENTH:1|"+s+"|"+s.sourceCode+"|"+s.parser+"|"+s.host+"|"+s.fileHost+"|"+s.download+"|https443|same-request|preview-no-fetch|limit10|unknown-role|"+AttachmentProfileFingerprint.selectHash("PAGE:1",SeoulSeventhNoticePage.class)+"|"+AttachmentProfileFingerprint.selectHash("QUERY:1",CapitalThirdNoticePage.class),getClass());}
    @Override public String selectProviderCode(){return "LOCAL_GOV_NOTICE";}
    @Override public String selectProfileCode(){return code;}
    @Override public String selectProfileHash(){return hash;}
    @Override public List<SourceBinding> selectSourceBindings(){return List.of(new SourceBinding(site.sourceCode,site.parser));}
    @Override public Set<String> selectApprovedHosts(){return new HashSet<>(List.of(site.host,site.fileHost));}
    @Override public URI selectDetailUri(String id){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public Result selectDescriptors(String id,String html){throw new IllegalArgumentException("PROFILE_REQUIRED");}
    @Override public URI selectDetailUri(Source s){try{if(s==null||!selectProviderCode().equals(s.providerCode())||!site.sourceCode.equals(s.localSourceCode())||!site.parser.equals(s.listParserProfileCode())||s.sourceUrl()==null||s.sourceUrl().length()>4096||!normalizer.hash(normalizer.canonicalizeUrl(s.sourceUrl())).equals(s.providerNoticeId()))throw new IllegalArgumentException();return SeoulSeventhNoticePage.selectDetailUri(site,URI.create(s.sourceUrl()));}catch(IllegalArgumentException e){throw new IllegalArgumentException("PROFILE_REQUIRED");}}
    private boolean selectNumber(String s){return s!=null&&s.matches("[1-9][0-9]{0,14}");}
    private boolean selectSafeUri(URI u){return u!=null&&"https".equals(u.getScheme())&&(u.getPort()==-1||u.getPort()==443)&&u.getUserInfo()==null&&u.getFragment()==null&&u.equals(u.normalize())&&u.getRawPath()!=null&&u.getRawPath().equals(u.getPath());}
    @Override public boolean selectApprovedRequest(URI u){try{if(!selectSafeUri(u))return false;if(site.host.equals(u.getHost())&&site.path.equals(u.getPath()))return u.equals(SeoulSeventhNoticePage.selectDetailUri(site,u));if(!site.fileHost.equals(u.getHost())||!site.download.equals(u.getPath()))return false;var q=CapitalThirdNoticePage.selectParameters(u.getRawQuery());
        return switch(site){case SEOUL->q.keySet().equals(Set.of("srvcId","upperNo","fileTy","fileNo","bbsNo"))&&"BBSTY1".equals(q.get("srvcId"))&&"ATTACH".equals(q.get("fileTy"))&&"277".equals(q.get("bbsNo"))&&selectNumber(q.get("upperNo"))&&selectNumber(q.get("fileNo"));case SEOUL_JUNGGU->q.keySet().equals(Set.of("mode","bid","cid","fileIndex","filename"))&&"download".equals(q.get("mode"))&&"469".equals(q.get("bid"))&&selectNumber(q.get("cid"))&&selectNumber(q.get("fileIndex"))&&q.get("filename").matches("[A-Za-z0-9_-]{1,150}\\.[A-Za-z0-9]{1,10}");case YONGSAN->q.keySet().equals(Set.of("menuNo","atchFileId","fileSn"))&&"200233".equals(q.get("menuNo"))&&q.get("atchFileId").matches("[a-f0-9]{32}")&&selectNumber(q.get("fileSn"));};
    }catch(IllegalArgumentException e){return false;}}
    @Override public boolean selectApprovedRequest(Request initial,Request next){return initial!=null&&initial.equals(next)&&selectApprovedRequest(next);}
    private URI selectEncoded(URI u){var q=CapitalThirdNoticePage.selectParameters(u.getRawQuery());var out=new StringJoiner("&");q.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->out.add(e.getKey()+"="+URLEncoder.encode(e.getValue(),StandardCharsets.UTF_8).replace("+","%20")));return URI.create("https://"+u.getHost()+u.getPath()+"?"+out);}
    private URI selectFile(String raw,URI detail){if(raw==null||raw.length()>8192)throw new IllegalArgumentException();URI u=detail.resolve(raw);if(!site.download.equals(u.getPath())||!selectApprovedRequest(u))throw new IllegalArgumentException();var q=CapitalThirdNoticePage.selectParameters(u.getRawQuery());String id=CapitalThirdNoticePage.selectParameters(detail.getRawQuery()).get(site.idKey);if(site==Site.SEOUL&&!id.equals(q.get("upperNo"))||site==Site.SEOUL_JUNGGU&&!id.equals(q.get("cid")))throw new IllegalArgumentException();return selectEncoded(u);}
    private boolean selectSafeName(String n){return !n.isBlank()&&n.length()<=500&&!n.contains("/")&&!n.contains("\\")&&!n.contains("..")&&n.indexOf('\ufffd')<0&&n.codePoints().noneMatch(Character::isISOControl);}
    private String selectName(Element a){var label=a.clone();label.select("i").remove();String name=label.text().strip();if(site==Site.YONGSAN)name=name.replaceFirst("\\s*\\[용량:[0-9.,]+ (?:KByte|MByte|Byte)\\]$","").strip();if(!selectSafeName(name))throw new IllegalArgumentException();return name;}
    private boolean selectPreview(Element a,URI file,String name,URI detail){try{if(a.hasAttr("onclick")||a.hasAttr("formaction"))return false;var q=CapitalThirdNoticePage.selectParameters(file.getRawQuery());
        if(site==Site.SEOUL)return a.is("button.sib-button[type=button]")&&Set.of("preview","preListen").contains(a.attr("data-type"))&&name.equals(a.attr("data-name"))&&file.equals(selectFile(a.attr("data-url"),detail));
        URI u=URI.create(a.attr("href"));if(u.isAbsolute()||u.getRawAuthority()!=null||u.getFragment()!=null||!u.equals(u.normalize())||!u.getRawPath().equals(u.getPath()))return false;var p=CapitalThirdNoticePage.selectParameters(u.getRawQuery());
        if(site==Site.SEOUL_JUNGGU)return a.hasClass("btn_view")&&"/convert.jsp".equals(u.getPath())&&p.equals(Map.of("bid","469","cid",q.get("cid"),"fileIndex",q.get("fileIndex"),"filePath","469/","fileName",q.get("filename")));
        var expected=new HashMap<>(Map.of("viewType","CONTBODY","atchFileId",q.get("atchFileId"),"fileSn",q.get("fileSn")));if(p.containsKey("initTTS"))expected.put("initTTS","true");return a.hasClass("viewer-link")&&"/portal/singl/convert/convertToHtml.do".equals(u.getPath())&&p.equals(expected);
    }catch(IllegalArgumentException e){return false;}}
    private boolean selectSeoulMetadata(Element item,URI file,String name){var ps=item.select(":root > p");if(ps.size()!=1)return false;var p=ps.getFirst();var q=CapitalThirdNoticePage.selectParameters(file.getRawQuery());boolean matches="BBSTY1".equals(p.attr("data-srvcid"))&&"ATTACH".equals(p.attr("data-filety"))&&"277".equals(p.attr("data-downbbsno"))&&q.get("upperNo").equals(p.attr("data-upperno"))&&q.get("upperNo").equals(p.attr("data-downnttno"))&&q.get("fileNo").equals(p.attr("data-fileno"));var remainder=p.clone();remainder.select("a,span.sib-ico-set-file").remove();return matches&&!selectUnsafe(remainder)&&remainder.text().matches("\\([0-9.,]+ (?:KB Bytes|MB Bytes|Bytes), 다운로드: [0-9,]+ 회 ?\\)");}
    @Override public Result selectDescriptors(Source s,String html){URI detail=selectDetailUri(s);if(html==null||html.length()>1_000_000)return selectFailed("ATTACHMENT_DETAIL_UNAVAILABLE");var page=Jsoup.parse(html,detail.toASCIIString());Element cell;try{cell=SeoulSeventhNoticePage.selectAttachments(site,page).clone();}catch(IllegalArgumentException e){return selectFailed("ATTACHMENT_SELECTOR_CHANGED");}if(site==Site.YONGSAN)cell.select("script,style").remove();String items=site==Site.SEOUL?":root > div.sib-viw-file":site==Site.SEOUL_JUNGGU?":root > p.mb05":":root > div.item";var residual=cell.clone();residual.select(items).remove();boolean unresolved=selectResidual(residual),exceeded=false;var found=new LinkedHashMap<String,Descriptor>();String noticeId=CapitalThirdNoticePage.selectParameters(detail.getRawQuery()).get(site.idKey);
        for(var item:cell.select(items))try{String selector=site==Site.SEOUL?":root > p > a":site==Site.SEOUL_JUNGGU?":root > a:not(.btn_view)":":root > a.file";var anchors=item.select(selector);if(anchors.size()!=1)throw new IllegalArgumentException();var a=anchors.getFirst();if(a.hasAttr("onclick"))throw new IllegalArgumentException();URI fetch=selectFile(a.attr("href"),detail);String name=selectName(a);var q=CapitalThirdNoticePage.selectParameters(fetch.getRawQuery());String fileKey=site==Site.SEOUL?q.get("upperNo")+"\n"+q.get("fileNo"):site==Site.SEOUL_JUNGGU?q.get("cid")+"\n"+q.get("fileIndex"):q.get("atchFileId")+"\n"+q.get("fileSn"),id=normalizer.hash(fileKey),ext=name.substring(name.lastIndexOf('.')+1).toUpperCase(Locale.ROOT);boolean supported=Set.of("PDF","HWP","HWPX").contains(ext)&&(site!=Site.SEOUL_JUNGGU||q.get("filename").toLowerCase(Locale.ROOT).endsWith("."+ext.toLowerCase(Locale.ROOT)));var d=new Descriptor(fetch,new AttachmentSetEvidence.Locator(code,site.download,Map.of("attachmentId",id,"noticeId",noticeId)),name,supported?ext:null,"UNKNOWN",supported);
            if(found.containsKey(id)){if(!found.get(id).equals(d))unresolved=true;}else if(found.size()==10)exceeded=true;else found.put(id,d);
            var remainder=item.clone();remainder.select(selector).remove();String previews=site==Site.SEOUL?"button":site==Site.SEOUL_JUNGGU?"a.btn_view":"a.viewer-link";for(var preview:remainder.select(previews))if(selectPreview(preview,fetch,name,detail))preview.remove();if(site==Site.SEOUL){if(selectSeoulMetadata(item,fetch,name))remainder.select(":root > p").remove();else unresolved=true;}if(site==Site.SEOUL_JUNGGU)remainder.select("em.file").remove();if(selectResidual(remainder)||selectUnsafe(a))unresolved=true;
        }catch(IllegalArgumentException e){unresolved=true;}
        if(exceeded)return new Result("LIMIT_EXCEEDED",false,List.copyOf(found.values()),List.of("ATTACHMENT_FILE_LIMIT"));if(unresolved)return new Result("FAILED",false,List.copyOf(found.values()),List.of("ATTACHMENT_LINK_UNRESOLVED"));return new Result(found.isEmpty()?"NO_FILES":"FOUND",true,List.copyOf(found.values()),List.of());}
    private boolean selectUnsafe(Element e){return !e.select("button,input,img,iframe,form,object,embed,script,[onclick]").isEmpty();}
    private boolean selectResidual(Element e){return !e.text().isBlank()||selectUnsafe(e)||!e.select("a,[href]").isEmpty();}
    private Result selectFailed(String code){return new Result("FAILED",false,List.of(),List.of(code));}
}
