package com.saneb.common.error;

public enum ErrorCode {
    AUTH_REQUIRED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_FORBIDDEN,
    AUTH_PASSWORD_RESET_REQUIRED,
    VALIDATION_FAILED,
    INVALID_PAGE_REQUEST,
    INVALID_STATUS_TRANSITION,
    RESOURCE_NOT_FOUND,
    DUPLICATE_LOGIN_ID,
    DUPLICATE_BUSINESS_REGISTRATION_NO,
    ANNOUNCEMENT_NOT_APPROVED,
    VERIFICATION_NOT_VERIFIED,
    MATCHING_BLOCKED,
    PROGRESS_STEP_LOCKED,
    PROGRESS_CONDITION_NOT_MET,
    DB_CONSTRAINT_VIOLATION,
    INTERNAL_ERROR
}
