ALTER TABLE standard_document_fields
    ADD COLUMN is_condition_eligible boolean NOT NULL DEFAULT false;

CREATE INDEX ix_standard_document_fields_condition_eligible
    ON standard_document_fields (document_type_code, is_condition_eligible, sort_order);

UPDATE standard_document_fields
SET is_condition_eligible = true
WHERE (document_type_code, field_key) IN (
    ('BUSINESS_REGISTRATION', 'OPENING_DATE'),
    ('BUSINESS_REGISTRATION', 'WORKPLACE_REGION_CODE'),
    ('BUSINESS_REGISTRATION', 'BUSINESS_TYPE_CODE'),
    ('BUSINESS_REGISTRATION', 'TAX_TYPE_CODE'),
    ('VAT_TAX_BASE', 'SUPPLY_AMOUNT'),
    ('VAT_TAX_BASE', 'ANNUAL_REVENUE'),
    ('VAT_TAX_BASE', 'TAX_TYPE_CODE'),
    ('TAX_EXEMPT_INCOME', 'TOTAL_INCOME_AMOUNT'),
    ('INCOME_CERTIFICATE', 'COMPREHENSIVE_INCOME_AMOUNT'),
    ('INCOME_CERTIFICATE', 'TOTAL_INCOME_AMOUNT'),
    ('INCOME_CERTIFICATE', 'BUSINESS_INCOME_AMOUNT'),
    ('INCOME_CERTIFICATE', 'LABOR_INCOME_AMOUNT'),
    ('NATIONAL_TAX_PAID', 'NATIONAL_TAX_DELINQUENT'),
    ('NATIONAL_TAX_PAID', 'TAX_PAID_STATUS'),
    ('LOCAL_TAX_PAID', 'LOCAL_TAX_DELINQUENT'),
    ('LOCAL_TAX_PAID', 'TAX_PAID_STATUS'),
    ('RESIDENT_REGISTRATION', 'REGION_CODE'),
    ('RESIDENT_REGISTRATION', 'IS_HOUSEHOLDER'),
    ('RESIDENT_REGISTRATION', 'HOUSEHOLD_MEMBER_COUNT'),
    ('FAMILY_RELATION', 'HAS_SPOUSE'),
    ('FAMILY_RELATION', 'CHILD_COUNT'),
    ('FAMILY_RELATION', 'PARENT_COUNT'),
    ('HEALTH_INSURANCE_PAYMENT', 'RECENT_HEALTH_INSURANCE_PREMIUM'),
    ('HEALTH_INSURANCE_PAYMENT', 'MONTHLY_HEALTH_INSURANCE_PREMIUM'),
    ('HEALTH_INSURANCE_PAYMENT', 'ANNUAL_HEALTH_INSURANCE_PREMIUM'),
    ('HEALTH_INSURANCE_PAYMENT', 'INSURANCE_SUBSCRIBER_TYPE'),
    ('HEALTH_INSURANCE_QUALIFICATION', 'HEALTH_INSURANCE_BASIS_CODE'),
    ('HEALTH_INSURANCE_QUALIFICATION', 'DEPENDENT_STATUS'),
    ('HEALTH_INSURANCE_QUALIFICATION', 'WORKPLACE_INSURED_STATUS'),
    ('HEALTH_INSURANCE_QUALIFICATION', 'LOCAL_INSURED_STATUS')
);
