-- Seed announcement classification release v1 as DRAFT only.
-- DRAFT_DISABLED terms remain stored but cannot participate in classification.
-- NOT_A_RULE terms are intentionally absent, and V56 rules are not converted.

INSERT INTO announcement_source_classification_rule_releases (
    id,
    release_code,
    version_no,
    row_version,
    release_status_code,
    rule_snapshot_hash,
    combination_operator_code,
    body_unavailable_action_code,
    attachment_analysis_enabled,
    auto_activation_enabled,
    change_note
) VALUES (
    md5('announcement-classification-release-v1')::uuid,
    'ASCR-000001',
    1,
    0,
    'DRAFT',
    NULL,
    'AND',
    'REVIEW_REQUIRED',
    false,
    false,
    '2026-08-11 클라이언트 확정 정책 기반 초기 DRAFT. 첨부 분석 및 자동 활성화 미사용.'
);

WITH release AS (
    SELECT id
    FROM announcement_source_classification_rule_releases
    WHERE release_code = 'ASCR-000001'
), group_seed (
    group_code,
    group_name,
    group_kind_code,
    target_category_code,
    support_type_code,
    title_action_code,
    body_action_code,
    sort_order
) AS (
    VALUES
        ('PROTECTED_METADATA_AGENCY', '기관명 보호 구간', 'PROTECTED_METADATA', NULL, NULL, 'MASK_ONLY', 'MASK_ONLY', 10),
        ('AUTO_EXCLUDE_B_EXPORT', 'B1 수출·해외진출', 'AUTO_EXCLUDE_B', NULL, NULL, 'EXCLUDED', 'REVIEW_REQUIRED', 100),
        ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', 'B2 투자·스타트업·벤처', 'AUTO_EXCLUDE_B', NULL, NULL, 'EXCLUDED', 'REVIEW_REQUIRED', 110),
        ('AUTO_EXCLUDE_B_PROCUREMENT', 'B3 조달·혁신제품', 'AUTO_EXCLUDE_B', NULL, NULL, 'EXCLUDED', 'REVIEW_REQUIRED', 120),
        ('AUTO_EXCLUDE_B_ESG', 'B4 ESG·친환경 기술', 'AUTO_EXCLUDE_B', NULL, NULL, 'EXCLUDED', 'REVIEW_REQUIRED', 130),
        ('AUTO_EXCLUDE_B_ADMINISTRATIVE', 'B6 행정 잡공고', 'AUTO_EXCLUDE_B', NULL, NULL, 'EXCLUDED', 'REVIEW_REQUIRED', 140),
        ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', 'A1 제조형·기술형·제품형', 'REVIEW_A', NULL, NULL, 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 200),
        ('REVIEW_A_RESEARCH_DEVELOPMENT', 'A2 R&D·연구개발', 'REVIEW_A', NULL, NULL, 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 210),
        ('REVIEW_A_IP_CERTIFICATION', 'A3 특허·지식재산·인증', 'REVIEW_A', NULL, NULL, 'REVIEW_REQUIRED', 'REVIEW_REQUIRED', 220),
        ('TARGET_BUSINESS', '지원대상 사업자', 'TARGET', 'BUSINESS', NULL, 'TAG', 'TAG', 300),
        ('TARGET_PERSONAL', '지원대상 본인(개인)', 'TARGET', 'PERSONAL', NULL, 'TAG', 'TAG', 310),
        ('TARGET_SPOUSE', '지원대상 배우자', 'TARGET', 'SPOUSE', NULL, 'TAG', 'TAG', 320),
        ('TARGET_CHILD', '지원대상 자녀', 'TARGET', 'CHILD', NULL, 'TAG', 'TAG', 330),
        ('TARGET_PARENT', '지원대상 부모님', 'TARGET', 'PARENT', NULL, 'TAG', 'TAG', 340),
        ('SUPPORT_GENERAL_SUPPORT', '지원유형 일반 지원', 'SUPPORT_TYPE', NULL, 'GENERAL_SUPPORT', 'TAG', 'TAG', 400),
        ('SUPPORT_GRANT_SUBSIDY', '지원유형 지원금·보조금', 'SUPPORT_TYPE', NULL, 'GRANT_SUBSIDY', 'TAG', 'TAG', 410),
        ('SUPPORT_POLICY_FINANCE', '지원유형 정책자금·금융', 'SUPPORT_TYPE', NULL, 'POLICY_FINANCE', 'TAG', 'TAG', 420),
        ('SUPPORT_GUARANTEE', '지원유형 보증', 'SUPPORT_TYPE', NULL, 'GUARANTEE', 'TAG', 'TAG', 430),
        ('SUPPORT_INTEREST', '지원유형 이자 지원', 'SUPPORT_TYPE', NULL, 'INTEREST_SUPPORT', 'TAG', 'TAG', 440),
        ('SUPPORT_VOUCHER_BENEFIT', '지원유형 바우처·혜택', 'SUPPORT_TYPE', NULL, 'VOUCHER_BENEFIT', 'TAG', 'TAG', 450),
        ('SUPPORT_REFUND_REDUCTION', '지원유형 환급·감면', 'SUPPORT_TYPE', NULL, 'REFUND_REDUCTION', 'TAG', 'TAG', 460),
        ('CONTEXT_ANNOUNCEMENT', '공고 문맥', 'CONTEXT', NULL, NULL, 'CONTEXT_ONLY', 'CONTEXT_ONLY', 500),
        ('CONTEXT_HOUSEHOLD', '가구 문맥', 'CONTEXT', NULL, NULL, 'CONTEXT_ONLY', 'CONTEXT_ONLY', 510)
)
INSERT INTO announcement_source_classification_rule_groups (
    id,
    release_id,
    group_code,
    group_name,
    group_kind_code,
    target_category_id,
    support_type_id,
    title_action_code,
    body_action_code,
    sort_order,
    is_enabled
)
SELECT
    md5('announcement-classification-group-v1-' || group_seed.group_code)::uuid,
    release.id,
    group_seed.group_code,
    group_seed.group_name,
    group_seed.group_kind_code,
    target_category.id,
    support_type.id,
    group_seed.title_action_code,
    group_seed.body_action_code,
    group_seed.sort_order,
    true
FROM group_seed
CROSS JOIN release
LEFT JOIN announcement_target_categories AS target_category
  ON target_category.category_code = group_seed.target_category_code
LEFT JOIN announcement_support_types AS support_type
  ON support_type.support_type_code = group_seed.support_type_code;

CREATE TEMPORARY TABLE announcement_classification_seed_terms (
    seed_order integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_code varchar(80) NOT NULL,
    term_text varchar(200) NOT NULL,
    strength_code varchar(30) NOT NULL,
    match_mode_code varchar(30) NOT NULL DEFAULT 'NORMALIZED_PHRASE',
    is_enabled boolean NOT NULL DEFAULT true,
    is_discovery_term boolean NOT NULL DEFAULT false,
    discovery_order integer,
    is_classification_term boolean NOT NULL DEFAULT true
) ON COMMIT DROP;

-- Initial support-type candidates.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code, is_enabled,
    is_discovery_term, discovery_order
) VALUES
    ('SUPPORT_GENERAL_SUPPORT', '지원사업', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_GENERAL_SUPPORT', '지원', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GRANT_SUBSIDY', '지원금', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_GRANT_SUBSIDY', '보조금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GRANT_SUBSIDY', '장려금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GRANT_SUBSIDY', '보상금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '정책자금', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_POLICY_FINANCE', '정책금융', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '자금지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '융자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '융자지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '대출', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '대출지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '경영안정자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '긴급경영안정자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '운전자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '경영자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '시설자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '생활안정자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '민생자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '특례자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '창업자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '초기창업자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '재창업자금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '저금리 대출', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_POLICY_FINANCE', '대환대출', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '보증', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_GUARANTEE', '보증지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '특례보증', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '신용보증', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '보증료지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '보증료감면', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '보증료 지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_GUARANTEE', '보증료 감면', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_INTEREST', '이자지원', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_INTEREST', '대출이자지원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_INTEREST', '이차보전', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_INTEREST', '이자차액보전', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_VOUCHER_BENEFIT', '바우처', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_VOUCHER_BENEFIT', '쿠폰', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_VOUCHER_BENEFIT', '포인트', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_REFUND_REDUCTION', '환급', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('SUPPORT_REFUND_REDUCTION', '감면', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_REFUND_REDUCTION', '면제', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('SUPPORT_REFUND_REDUCTION', '할인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL);

-- Announcement and household context never satisfy a support type by themselves.
INSERT INTO announcement_classification_seed_terms (group_code, term_text, strength_code) VALUES
    ('CONTEXT_ANNOUNCEMENT', '사업공고', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '시행공고', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '모집공고', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '참여자 모집', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '참여기업 모집', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '대상자 모집', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '신청자 모집', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '신청', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '접수', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '접수기간', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '신청기간', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '신청방법', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '지원대상', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '지원내용', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '지원금액', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '지원규모', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '제출서류', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '선정', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '선정자', 'STRONG'),
    ('CONTEXT_ANNOUNCEMENT', '선정기업', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '가구', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '가구원', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '세대', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '건강보험료', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '기준중위소득', 'STRONG'),
    ('CONTEXT_HOUSEHOLD', '재산기준', 'STRONG');

-- Target categories. Only representative strong terms participate in provider discovery.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code, is_enabled,
    is_discovery_term, discovery_order
) VALUES
    ('TARGET_BUSINESS', '소상공인', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('TARGET_BUSINESS', '자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '개인사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '사업주', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '영세사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '영세 소상공인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '영세 자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '1인 사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '1인 자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '프리랜서 사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '특수고용', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '특고', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '플랫폼 종사자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '전통시장 상인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '상점가 상인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 소상공인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 개인사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 업체', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 점포', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '관내 사업장', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '해당 지역 사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '해당 지역 소상공인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '해당 지역 자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '해당 지역 개인사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '예비창업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '창업예정자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '초기창업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '창업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '폐업 소상공인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '폐업 자영업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '폐업 사업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '재창업자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '대표자', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '프리랜서', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '플랫폼 노동자', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '상인', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '점포', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '사업장', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '사업체', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '업체', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_BUSINESS', '기업', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '청년', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('TARGET_PERSONAL', '중장년', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '고령자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '여성', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '장애인', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '북한이탈주민', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '새터민', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '탈북민', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '다문화', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '한부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '저소득', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '차상위', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '기초생활수급자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '취약계층', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '취업취약계층', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '실직', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '구직', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '거주자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '국민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '대한민국 국민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '주민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '시민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '군민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '구민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '도민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '지역주민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '관내 주민', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '관내 거주자', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PERSONAL', '해당 지역 거주', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '배우자', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('TARGET_SPOUSE', '남편', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '아내', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '소상공인 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '자영업자 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '사업자 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '개인사업자 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '사업주 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '대표자 배우자', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '신혼부부', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '신혼가구', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_SPOUSE', '경력단절 여성', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '경단녀', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '여성새로일하기', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '새일센터', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '난임', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '난임지원', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '난임시술', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '난임시술비', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_SPOUSE', '출산가구', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_CHILD', '자녀', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('TARGET_CHILD', '소상공인 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '자영업자 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '사업자 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '개인사업자 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '사업주 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '대표자 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '아동', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '영유아', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '유아', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '어린이', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '청소년', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '학생', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '초등학생', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '중학생', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '고등학생', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '대학생', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '미성년 자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '다자녀', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '어린이집', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '유치원', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '초등학교', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '중학교', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '고등학교', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '대학교', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '출산', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '양육', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '보육', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '육아', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '아이돌봄', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_CHILD', '돌봄', 'SUPPLEMENTARY', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '부모님', 'STRONG', 'NORMALIZED_PHRASE', true, true, 1),
    ('TARGET_PARENT', '부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '아버지', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '어머니', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '사업자 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '소상공인 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '자영업자 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '개인사업자 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '사업주 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '대표자 부모님', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '직계존속', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '노부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '고령 부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '고령부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '어르신 부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '노인 부모', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '부모 부양', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '부모님 부양', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '직계존속 부양', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '노부모 부양', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '고령부모 부양', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL),
    ('TARGET_PARENT', '어르신', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '노인', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '65세 이상', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '70세 이상', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '독거노인', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '노인돌봄', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '노인일자리', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL),
    ('TARGET_PARENT', '기초연금', 'STRONG', 'NORMALIZED_PHRASE', false, false, NULL);

-- Group A: always review, never auto-delete.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code
) VALUES
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제조형 사업자', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제조기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제조업체', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술형 사업자', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술창업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술기반 창업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술사업화', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '기술개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제품형 사업자', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제품개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '시제품', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '시제품 제작', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '시제품 개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '양산지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '생산지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '생산설비', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '설비지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '설비자동화', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '공장자동화', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '스마트공장', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '스마트팩토리', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '자동화설비', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '제조공정', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '공정개선', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '공정자동화', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '소재부품장비', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '소부장', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '부품개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_MANUFACTURING_TECH_PRODUCT', '장비개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', 'R&D', 'STRONG', 'TOKEN'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '연구개발', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '연구과제', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '기술연구', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '개발과제', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '국책과제', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '정부과제', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '과제수행', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '연구비지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '기술개발지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '연구개발지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '산학협력', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '산학연', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '기업부설연구소', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '연구소', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '전담연구부서', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '실증사업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '실증지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '테스트베드', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', 'PoC', 'STRONG', 'TOKEN'),
    ('REVIEW_A_RESEARCH_DEVELOPMENT', '개념검증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '특허', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '실용신안', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '상표', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '디자인권', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '저작권', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '지식재산', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '지식재산권', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', 'IP', 'STRONG', 'TOKEN'),
    ('REVIEW_A_IP_CERTIFICATION', 'IP지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '특허출원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '상표출원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '디자인출원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '특허등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '상표등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '지식재산 컨설팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', 'IP 컨설팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '인증획득', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '인증지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '인증비 지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '인증 컨설팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', 'ISO', 'STRONG', 'TOKEN'),
    ('REVIEW_A_IP_CERTIFICATION', 'HACCP', 'STRONG', 'TOKEN'),
    ('REVIEW_A_IP_CERTIFICATION', 'KC인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', 'KS인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', 'NET', 'STRONG', 'TOKEN'),
    ('REVIEW_A_IP_CERTIFICATION', 'NEP', 'STRONG', 'TOKEN'),
    ('REVIEW_A_IP_CERTIFICATION', '벤처기업 인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '이노비즈', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '메인비즈', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '기업인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '품질인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '해외인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('REVIEW_A_IP_CERTIFICATION', '수출인증', 'STRONG', 'NORMALIZED_PHRASE');

-- Group B: title EXCLUDED, body-only REVIEW_REQUIRED.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code
) VALUES
    ('AUTO_EXCLUDE_B_EXPORT', '수출', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출지원', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출바우처', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출상담회', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출역량강화', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출마케팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외진출', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외시장', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외마케팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외전시', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외박람회', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외규격인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외판로', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '글로벌 진출', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '글로벌 마케팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '바이어 상담', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '무역사절단', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '통상촉진단', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '해외바이어', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출초보기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_EXPORT', '수출유망기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '스타트업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '벤처', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '벤처기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '벤처창업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '기술창업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '딥테크', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '초격차', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', 'TIPS', 'STRONG', 'TOKEN'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '팁스', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '투자유치', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', 'IR', 'STRONG', 'TOKEN'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', 'IR피칭', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '데모데이', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '액셀러레이팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '액셀러레이터', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '창업보육', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '보육기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '입주기업 모집', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '창업보육센터', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '스케일업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '오픈이노베이션', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '혁신창업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '혁신기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '성장기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_INVESTMENT_STARTUP', '고성장기업', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '혁신제품', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '우수제품', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '조달등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '나라장터 등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '조달청 등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '공공조달 등록', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '공공조달 컨설팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', 'MAS', 'STRONG', 'TOKEN'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '다수공급자계약', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '우수조달물품', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '벤처나라', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '혁신장터', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '조달혁신', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_PROCUREMENT', '조달시장 진출', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', 'ESG', 'STRONG', 'TOKEN'),
    ('AUTO_EXCLUDE_B_ESG', 'ESG 경영', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', 'ESG 컨설팅', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '친환경 기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '녹색기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '탄소중립 기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '탄소저감 기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '온실가스 감축', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '에너지효율 기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '환경기술', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '친환경 인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '녹색인증', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '탄소중립 설비', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ESG', '저탄소 제품', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공무원 채용', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공무직 채용', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '기간제근로자 채용', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '임기제공무원 채용', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '합격자 발표', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '면접시험', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '채용시험', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공사 입찰', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '용역 입찰', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '물품구매 입찰', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '입찰 결과', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '개찰 결과', 'STRONG', 'NORMALIZED_PHRASE'),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '낙찰자', 'STRONG', 'NORMALIZED_PHRASE');

-- B6 unconfirmed remainder is present only as disabled DRAFT data.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code, is_enabled
) VALUES
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '수의계약', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '견적제출', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '계약체결', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '제안서 평가위원', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '평가위원 모집', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '평가위원 후보자', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '제안서 접수', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '용역공고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공사공고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '기간제근로자', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '기간제 근로자', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '임기제공무원', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '임기제 공무원', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '무기계약직', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공공근로 채용', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '최종합격자', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '서류전형 합격', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '면접대상자', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '시험공고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '필기시험', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '개찰', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '낙찰', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공무원 시험', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '인사발령', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '승진', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '전보', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '복무', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '징계', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '감사결과', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '감사', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '의회', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '조례', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '규칙', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '훈령', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '예규', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '행정예고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '입법예고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공시송달', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '처분사전통지', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '과태료', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '체납', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '압류', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '무단방치', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '도로명주소', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '도시계획', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '건축허가 취소', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '영업정지', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '행정처분', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '폐기물처리', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '불법주정차', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '주민등록 말소', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '주민등록 최고', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '개별공시지가', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '공시지가', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '토지수용', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '보상계획 열람', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '환경영향평가', 'STRONG', 'NORMALIZED_PHRASE', false),
    ('AUTO_EXCLUDE_B_ADMINISTRATIVE', '재해영향평가', 'STRONG', 'NORMALIZED_PHRASE', false);

-- B5 agency terms create protected metadata ranges only.
INSERT INTO announcement_classification_seed_terms (
    group_code, term_text, strength_code, match_mode_code, is_enabled,
    is_discovery_term, discovery_order, is_classification_term
) VALUES
    ('PROTECTED_METADATA_AGENCY', '기보', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '기술보증기금', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '중진공', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '중소벤처기업진흥공단', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '중소기업기술정보진흥원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', 'TIPA', 'STRONG', 'TOKEN', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '산업기술진흥원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', 'KIAT', 'STRONG', 'TOKEN', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '산업기술평가관리원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', 'KEIT', 'STRONG', 'TOKEN', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '창업진흥원', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '한국산업단지공단', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '무역협회', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', 'KOTRA', 'STRONG', 'TOKEN', true, false, NULL, false),
    ('PROTECTED_METADATA_AGENCY', '코트라', 'STRONG', 'NORMALIZED_PHRASE', true, false, NULL, false);

-- One rule owns one canonical term in this seed; explicit aliases are added below as SYNONYM terms.
WITH numbered_seed AS (
    SELECT
        seed.*,
        row_number() OVER (PARTITION BY seed.group_code ORDER BY seed.seed_order) AS group_rule_order
    FROM announcement_classification_seed_terms AS seed
)
INSERT INTO announcement_source_classification_keyword_rules (
    id,
    group_id,
    rule_code,
    strength_code,
    is_enabled,
    sort_order,
    row_version
)
SELECT
    md5(
        'announcement-classification-rule-v1-'
        || seed.group_code || '-' || lower(seed.term_text)
    )::uuid,
    rule_group.id,
    seed.group_code || '_' || lpad(seed.group_rule_order::text, 3, '0'),
    seed.strength_code,
    seed.is_enabled,
    seed.group_rule_order * 10,
    0
FROM numbered_seed AS seed
JOIN announcement_source_classification_rule_groups AS rule_group
  ON rule_group.release_id = md5('announcement-classification-release-v1')::uuid
 AND rule_group.group_code = seed.group_code;

INSERT INTO announcement_source_classification_keyword_terms (
    id,
    keyword_rule_id,
    group_id,
    term_type_code,
    term_text,
    normalized_term_text,
    match_mode_code,
    is_discovery_term,
    discovery_order,
    is_classification_term,
    is_enabled
)
SELECT
    md5(
        'announcement-classification-term-v1-canonical-'
        || seed.group_code || '-' || lower(seed.term_text)
    )::uuid,
    rule.id,
    rule_group.id,
    'CANONICAL',
    seed.term_text,
    btrim(regexp_replace(
        regexp_replace(lower(seed.term_text), '[^0-9a-z가-힣]+', ' ', 'g'),
        '[[:space:]]+',
        ' ',
        'g'
    )),
    seed.match_mode_code,
    seed.is_discovery_term,
    seed.discovery_order,
    seed.is_classification_term,
    seed.is_enabled
FROM announcement_classification_seed_terms AS seed
JOIN announcement_source_classification_rule_groups AS rule_group
  ON rule_group.release_id = md5('announcement-classification-release-v1')::uuid
 AND rule_group.group_code = seed.group_code
JOIN announcement_source_classification_keyword_rules AS rule
  ON rule.group_id = rule_group.id
 AND rule.id = md5(
        'announcement-classification-rule-v1-'
        || seed.group_code || '-' || lower(seed.term_text)
    )::uuid;

WITH synonym_seed (synonym_text, canonical_text) AS (
    VALUES
        ('기간제 근로자 채용', '기간제근로자 채용'),
        ('임기제 공무원 채용', '임기제공무원 채용'),
        ('물품 구매 입찰', '물품구매 입찰')
)
INSERT INTO announcement_source_classification_keyword_terms (
    id,
    keyword_rule_id,
    group_id,
    term_type_code,
    term_text,
    normalized_term_text,
    match_mode_code,
    is_discovery_term,
    discovery_order,
    is_classification_term,
    is_enabled
)
SELECT
    md5('announcement-classification-term-v1-synonym-b6-' || lower(synonym.synonym_text))::uuid,
    canonical.keyword_rule_id,
    canonical.group_id,
    'SYNONYM',
    synonym.synonym_text,
    btrim(regexp_replace(
        regexp_replace(lower(synonym.synonym_text), '[^0-9a-z가-힣]+', ' ', 'g'),
        '[[:space:]]+',
        ' ',
        'g'
    )),
    'NORMALIZED_PHRASE',
    false,
    NULL,
    true,
    true
FROM synonym_seed AS synonym
JOIN announcement_source_classification_rule_groups AS rule_group
  ON rule_group.release_id = md5('announcement-classification-release-v1')::uuid
 AND rule_group.group_code = 'AUTO_EXCLUDE_B_ADMINISTRATIVE'
JOIN announcement_source_classification_keyword_terms AS canonical
  ON canonical.group_id = rule_group.id
 AND canonical.term_type_code = 'CANONICAL'
 AND canonical.term_text = synonym.canonical_text;

-- The temporary seed table is dropped automatically at transaction commit.
